### PR TITLE
fixes issue #2310 - fixes reading geojson with column called geometry

### PR DESCRIPTION
**Pull request by phildias**
This PR would change the behavior of the `GeoDataFrame.from_features()` method to allow reading GeoJSON strings that contain a column called "geometry" in the attribute table. This would address issue #2310.

### CODE REVIEW

**Comment by phildias** [comment]
Sorry, I'm not sure why the linting test is failing. Any ideas what's causing the issue?

**Comment by martinfleis** [comment]
If you check the log here https://github.com/geopandas/geopandas/runs/4875456679?check_suite_focus=true you can see in red lines that are wrong and in green how they're supposed to look like. For more, see the [contributing docs.](https://geopandas.org/en/latest/community/contributing.html#style-guide-linting)

**Comment by phildias** [comment]
Ah, fantastic! Thank you! I was able to fix the linting issues. Now I just need to find how to fix the tests that fail when `PyGeos` isn't installed.

**Comment by martinfleis** [comment]
There are two aspects to this PR.

1) Allow custom geometry column name in `from_features`

I think that this is useful, you may want to read your features and get a df with differently named active geometry column than the default hardcoded `"geometry"`. That will also allow fixing #2310.

2) Automatic renaming of conflicting column names

I don't think we want to do this. We should still raise in that case but allow users to manually specify how the geometry column should be called using 1).

**Comment by phildias** [comment]
Thanks for the feedback! I can definitely edit the PR to remove the part where I try to "fix" the column name.

**Comment by jorisvandenbossche** [comment]
Agreed with what @martinfleis said, and to add: we should try to ensure we give a clear error message. The current one is already clear that there is a problem with 2 "geometry" columns, but we could try to append that message with saying something like "you can specify this keyword ... to rename the geometry column and prevent this error" or something like that.

**Comment by phildias** [comment]
I'm closing this PR. Somehow, the new fixes I made got added to [another PR](https://github.com/geopandas/geopandas/pull/2328): #2328 . Apologies for the inconvenience.

**Pull request closed without merging**
