### PR TITLE
TST/BUG: fix assert_geodataframe_equal to handle no-active-geometry corner cases

### LINKED ISSUE #2333: TST: assert_geodataframe_equal checks non active geometry columns twice
https://github.com/geopandas/geopandas/blob/a80081e52ed3bd069a75a4caaed44e45e35c647d/geopandas/testing.py#L318-L333

checks non active geometry columns twice. We should be able to drop all columns of geometrydtype for left2 and right2.

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
xref https://github.com/geopandas/geopandas/pull/2497#issuecomment-1186442292

The test I added is still failing as it will be fixed by https://github.com/geopandas/geopandas/pull/2497

Closes #2333

### CODE REVIEW

**Comment by m-richards** [comment]
I haven't had a properly look at this PR yet, but it seems to also fix #2333.

**Review by m-richards — COMMENTED** [review]
Looks good, but it appears that there is another edge case in pivot causing the failure in the tests, geometry column name is not preserved (but at least it no longer crashes which is an improvement). Not sure what the best way forward is for this, ignore the pivot case for now and solve that separately, and then update that test to use the updated assert_geodataframe_equal?

**Comment by jorisvandenbossche** [comment]
> I think this is actually right - there's no use in keeping "geometry" as the active geometry column 

Yes, agreed that the result of pivot is looking ok now. And the way we create

**Review by m-richards — APPROVED** [review]
Looks good to me!

**Review by martinfleis — APPROVED** [review]
Thanks! I've committed a changelog note.

**Comment by martinfleis** [comment]
Thanks @jorisvandenbossche!

**Pull request merged**
