### PR TITLE
DOC: Prompt Contributor to Install Pre-commit

### PR DESCRIPTION
**Pull request by rdmolony**
I for one keep forgetting to blacken my code prior to submitting a PR which wastes CI resources needlessly...

If usage of `pre-commit` was forced upon me I could have skipped this as `black` would be run automatically.

This PR is prompted by me forgetting to blacken my code during #1610...

### CODE REVIEW

**Comment by Sangarshanan** [comment]
oh but isn't this already on the style guide? https://github.com/geopandas/geopandas/blob/master/doc/source/community/contributing.rst#style-guide--linting

**Comment by rdmolony** [comment]
Its recommended at the bottom of contributing :) this PR proposes including it in the 7 steps to raise it during conda env setup but perhaps at the end suffices so not necessary

**Comment by martinfleis** [comment]
I would keep it where it is now, @Sangarshanan is right that it is already there. No need to repeat it above.

> which wastes CI resources needlessly

We have now quick required check for style before tests actually start in CI, so this is no longer an issue. CI fails and stops in about 20 seconds if there's an issue.

**Comment by rdmolony** [comment]
Sounds good to me 🙂

**Pull request closed without merging**
