### PR TITLE
ENH: Add GeometryArray._from_sequence_of_strings

### LINKED ISSUE #3099: ENH: Add _from_sequence_of_strings for GeometryArray
#### Describe the solution you'd like
Currently passing `dtype={"geometry": "geometry"}` to e.g. `read_csv` fails:
```
import geopandas as gpd
gpd.read_file(gpd.datasets.get_path('nybb')).to_crs("epsg:4326").to_csv("/tmp/boros.csv", index=False)
pd.read_csv("/tmp/boros.csv", dtype={"geometry": "geometry"})
...
NotImplementedError: Extension Array: <class 'geopandas.array.GeometryArray'> must implement _from_sequence_of_strings in order to be used in parser methods
```
It seems like just setting this to call `from_wkt` works fine?
```
gpd.array.GeometryArray._from_sequence_of_strings = gpd.GeoSeries.from_wkt
pd.read_csv("/tmp/boros.csv", dtype={"geometry": "geometry"})
   BoroCode       BoroName  ...    Shape_Area                                           geometry
0         5  Staten Island  ...  1.623820e+09  MULTIPOLYGON (((-74.05050806403247 40.56642203...
1         4         Queens  ...  3.045213e+09  MULTIPOLYGON (((-73.83668274106707 40.59494669...
2         3       Brooklyn  ...  1.937479e+09  MULTIPOLYGON (((-73.86706149472118 40.58208797...
3         1      Manhattan  ...  6.364715e+08  MULTIPOLYGON (((-74.01092841268031 40.68449147...
4         2          Bronx  ...  1.186925e+09  MULTIPOLYGON (((-73.89680883223774 40.79580844...

[5 rows x 5 columns]
```

#### API breaking implications

[this should provide a description of how this feature will affect the API]

#### Describe alternatives you've considered

[this should provide a description of any alternative solutions or features you've considered]

#### Additional context

[add any other context, code examples, or references to existing implementations about the feature request here]

```python
# Your code here, if applicable

```

### PR DESCRIPTION
**Pull request by bnaul**
Closes #3099.

Like `_from_sequence` right above, I minimally edited the abstract base function to give the desired behavior.

@martinfleis think this warrants its own test since it's more or less an alias of `from_wkt`...?

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
I think it would be good to add a small test that reading from CSV with specifying the dtype works (essentially what you did in the issue). While we indeed don't need to test the details of what kind of strings work for `from_wkt`, it's good to have some test to avoid accidentally removing this feature.

**Comment by bnaul** [comment]
Makes sense, added!

**Comment by bnaul** [comment]
@jorisvandenbossche believe this is ready, I think the test failure is unrelated

**Comment by martinfleis** [comment]
Looks good to me! Can you also add a short line to the changelog?

**Review by m-richards — APPROVED** [review]

**Review by jorisvandenbossche — APPROVED** [review]

**Comment by bnaul** [comment]
@martinfleis done!

**Review by martinfleis — APPROVED** [review]
Thanks @bnaul!

**Pull request merged**
