### PR TITLE
DOC: switch examples to nbsphinx

### LINKED ISSUE #280: DOC: include example notebooks in sphinx docs
For greater visibility of those notebooks.

Several options I think: more manually converting with nbconvert to rst and including that (but can be automated, I think statsmodels does this), or maybe look into something like https://nbsphinx.readthedocs.org/en/0.2.5/

### LINKED ISSUE #1052: DOC: Some methods (explode, collect) are missing in docs
There are couple of methods in the code which are not included in the documentation (even though they have docstrings) like `explode()` and `collect()`. We should check which methods are missing and add them to reference guide and at least `explode()` should be included in the user guide as well.

I will do that myself, I just wanted to point out that it is happening, so we can think about possible prevention in the future.

### PR DESCRIPTION
**Pull request by martinfleis**
There has been long ongoing issue with majority of examples not being included in docs as they were Jupyter notebooks instead of .py files prepared for sphinx gallery extension. I have now changed the way how examples are handled.

- all examples are Jupyter notebooks now
- all are within `doc/source` - there is no way to load them from original `examples` folder
- all are executed by sphinx to get fresh outputs
- all can be run interactively on mybinder
- interactivity (folium) works
- links to existing examples in gallery are still the same

The downward is a bit more complicated diff for `.ipynb` files than `.py`. But I think that Jupyter notebooks are better way forward that sphinx-gallery py files.

~I have also added missing methods to reference guide.~ (see #1328)

related to #1076, closes #280

### CODE REVIEW

**Comment by awa5114** [comment]
#1052 still looks open to me... Shouldn't someone close it if this addresses the problem?

**Comment by martinfleis** [comment]
@awa5114 it will be closed once this PR is merged.

**Comment by Sangarshanan** [comment]
@martinfleis Any plans to get this merged? It would really cool to add more interactive maps to docs ref: #280

**Comment by martinfleis** [comment]
@Sangarshanan hopefully yes. I'll give it one more try to link it from `examples` folder, but I wasn't able to do it last time for certain reasons.

It is not a priority, so it may take some time before it gets merged.

**Comment by Sangarshanan** [comment]
Sure...would love to help if possible

**Pull request closed without merging**
