### PR TITLE
ENH: Allow setting geometry property via XY coords (two columns)

### PR DESCRIPTION
**Pull request by carsonfarmer**
This PR allows the user to specify two columns (X and Y) to the `set_geometry` method. This will allow a DataFrame with Lat, Lon, fields to be easily converted to a GeoDataFrame.

``` python
df = GeoDataFrame({"A": [1,2,3,4,5,6],
                               "B": [6,5,4,3,2,1],
                               "X": [1,2,3,4,5,6],
                               "Y": [1,2,3,4,5,6]})
df.set_geometry(["X", "Y"], inplace=True, drop=False)
```

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
I just wanted to open an issue for this feature, so it would be very nice to revive this!

@carsonfarmer Do you have time for this? 
@kjordahl Is this good? Are there other things needed?

**Comment by jdmcbr** [comment]
Though this now has conflicts to be resolved, I'd still be interested in seeing this, or something like it, implemented.

**Comment by poplarShift** [comment]
+1!

@carsonfarmer In case you shouldn't have time to resolve the conflicts and update the PR, I'd be happy to "take over" (except I don't know how I can commit changes to your PR...)

@jorisvandenbossche

**Comment by carsonfarmer** [comment]
@poplarShift unfortunately, I don't have time to work on this further. Feel free to take over. I think probably the easiest way to do so is to fork, checkout this branch, make your updates, and submit a new pr. Then let me know and I'll link to your new PR and close this one. I think probably @jorisvandenbossche or others will be more responsive than myself or @kjordahl.

**Comment by jdmcbr** [comment]
Superseded by #896

**Pull request closed without merging**
