### PR TITLE
TST: update comments in tests after #2329

### PR DESCRIPTION
**Pull request by m-richards**
Follow-up on https://github.com/geopandas/geopandas/pull/2329, updating the test (comments) to reflect the decision we made in https://github.com/geopandas/geopandas/issues/2133

### CODE REVIEW

**Comment by m-richards** [comment]
The compat comment should have been deleted in previous PR - This was from before Martin bumped the minimum pandas version and it wasn't deleted when the if (version) check was removed.

**Comment by m-richards** [comment]
Fairly sure these test failures are unrelated - I've only changed stuff in another test file, not really sure what is going on, it's like the crs projections / how check_less precise works is now different?

**Comment by jorisvandenbossche** [comment]
> Fairly sure these test failures are unrelated - I've only changed stuff in another test file, not really sure what is going on, it's like the crs projections / how check_less precise works is now different?

Yes, there were some test issues related to a new PROJ release

**Comment by jorisvandenbossche** [comment]
The remaining mac failure is a known issue with the conda env

**Review by jorisvandenbossche — APPROVED** [review]
Thanks!

**Pull request merged**
