### PR TITLE
ENH: use row.name for id when exporting to GeoJSON

### PR DESCRIPTION
**Pull request by ResidentMario**
#390 asks that exporting an ID when exporting to GeoJSON be made an optional thing, per the specification. However, @sgillies (who is actually on the spec committee) stepped in and pointed out that this was due to a lack of consensus regarding an error correction in the previous spec and that actually having a meaningful ID is part of best practices.

In light of that I'm opposed to making exporting an ID optional, and in favor of making the ID exported meaningful. This PR is a tiny change that does the latter by replacing `str(i)` (the column number) with `str(row.name)` (the column index entry) in the export.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Looking at the `iterrows` docstring, this returns (index, Series) pairs. So this actually already works:

```
In [20]: import geopandas

In [22]: from shapely.geometry import Point

In [24]: gdf = geopandas.GeoDataFrame({'a': [1,2]}, geometry=[Point(1,1), Point(2,2)], index=['a', 'b'])

In [25]: gdf
Out[25]: 
   a     geometry
a  1  POINT (1 1)
b  2  POINT (2 2)

In [26]: gdf.iterfeatures()
Out[26]: <generator object GeoDataFrame.iterfeatures at 0x7fc5796467d8>

In [27]: list(gdf.iterfeatures())
Out[27]: 
[{'geometry': {'coordinates': (1.0, 1.0), 'type': 'Point'},
  'id': 'a',
  'properties': {'a': 1},
  'type': 'Feature'},
 {'geometry': {'coordinates': (2.0, 2.0), 'type': 'Point'},
  'id': 'b',
  'properties': {'a': 2},
  'type': 'Feature'}]
```

**Comment by ResidentMario** [comment]
I don't see exactly where it's doing that, but it looks like you're right.

You can close this PR, or maybe merge it (maybe this is a bit more explicit?), whichever.

**Comment by jorisvandenbossche** [comment]
> I don't see exactly where it's doing that

It is just what `iterrows` does (docstring: "Iterate over DataFrame rows as (index, Series) pairs."). You can look in the iterrows source to see it.

> maybe merge it (this is a bit more explicit?), whichever.

what you could do to make it more explicit it change `i, row in self.iterrows()` in `name, row in self.iterrows()`

Would maybe also be nice to add a test for this.

**Comment by ResidentMario** [comment]
Ah, I see. Changed the iterator to `name` so it's more explicit.

This is a minor detail, I don't think it's worth testing. Probably just change `i` to `name` and leave it at that.

**Pull request merged**
