### PR TITLE
ENH/VIS: add legend for choropleth plots

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Based on a SO question, I added the ability to create a legend for choropleth figures based on PySAL schemes (see my answer: http://stackoverflow.com/questions/31755886/choropleth-map-from-geopandas-geodatafame?noredirect=1#comment51555293_31755886 and the notebook: http://nbviewer.ipython.org/gist/jorisvandenbossche/d4e6efedfa1e4e91ab65)

This lets you obtain something like:

index

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
One thing: the fall-back to the values itself when PySAL is not installed will now fail with the current code (I return the `binning`, as I need this for the labels of the legend). Is it OK that I change the print statement in an error that you need PySAL installed for using the `scheme` functionality? This would make it a lot easier than trying to detect in `plot_dataframe` if the binning succeeded or not (because it depends on that if the legend is categorical or continuous).

**Comment by kjordahl** [comment]
@jorisvandenbossche Yes, I agree that raising an error would be better than falling back and just printing a message. Please go ahead and do it.

**Comment by jorisvandenbossche** [comment]
@kjordahl I changed it to error on import. 

I also changed the other print statements to warnings, is that OK?

**Comment by jorisvandenbossche** [comment]
@kjordahl I rebased this and added a test. So for me it is ready to merge. Or is there anything else needed?

**Comment by jorisvandenbossche** [comment]
The travis failures seems not to be related to this PR, but the installation of shapely fails ..

**Comment by kjordahl** [comment]
I think the test failure was an issue with a Shapely release that's now been resolved.

I restarted the Travis run and all looks good now.

Thanks!

**Pull request merged**
