### PR TITLE
ENH df.set_geometry() using coordinates

### PR DESCRIPTION
**Pull request by poplarShift**
.set_geometry() now takes keywords x, y[, z] as an alternative to the `col` argument to construct the geometry column directly from coordinates.

Most of the code here was taken from PR #75 which is superseded by this PR.

### CODE REVIEW

**Comment by poplarShift** [comment]
Also fixes my earlier request on the pandas side, see pandas-dev/pandas#22822, from where @jorisvandenbossche directed me here.

**Comment by poplarShift** [comment]
Anything I can do to get someone to look at this @jorisvandenbossche ? In hindsight I can see I should do a bit more linting for PEP8 but is there anything apart from that?

**Comment by jorisvandenbossche** [comment]
@poplarShift sorry for the slow follow-up (and thanks for working on it!)

I think for me the main question is if we are happy with the exact API. Options:

* Additional `x`, `y` (and `z`) keywords to `set_geometry` (like `set_geometry(x='x', y='y')`, as in this PR)
* Allowing a list of columns names instead of a single column name (like `set_geometry(['x', 'y'])`)

The first is certainly more explicit (and less corner cases to check, as the first argument also can be a list of actual geometries). 
But the reason I am hesitating a bit is that it might be nice to also support this directly in `GeoDataFrame(..., geometry=['x', 'y'])` (and there I am not sure we should add the additional keywords, although that is actually also possible).

In dask-geopandas, the option was to pass an actual dataframe of two columns, like `set_geometry(df[['x', 'y']])`.

**Comment by jorisvandenbossche** [comment]
Thanks for the input!

> maybe I'm missing the point here.

I think the main 'point's are:

1) convenience: this is such a typical use case that needing to know that you can apply `Point` on the rows of a DataFrame with `apply` when selecting the two columns is a bit cumbersome (although an example in the docs helps a lot in that case: https://geopandas.readthedocs.io/en/latest/gallery/create_geopandas_from_pandas.html#from-longitudes-and-latitudes)

2) (potential) speed. By having this a built-in method, and not relying on the user the apply `Point` manually, this can potentially be speed-up a lot in a cythonized/numba version, as we can much more efficiently create those points all at once.

But of course, that doesn't mean this built-in method necessarily needs to be `set_geometry`. It could also be something else, like the `infer_geometry` as you mention (although I would personally not start any 'inferring', but requiring the user to be explicit about what it can pass). 

Other possibility might be a separate function like `from_xy` or `points_from_xy` that returns a GeoSeries (or GeometryArray after the refactor) and that can be passed into a GeoDataFrame as well). Something like:

```
gdf = geopandas.GeoDataFrame(df, geometry=geopandas.from_xy(df['x'], df['y']))
```

Disadvantage (or advantage depending on what you want :-)) is that here the x/y columns would not be dropped from `gdf` (or no option to do it) as opposed to how `set_geometry` now works.

**Comment by jorisvandenbossche** [comment]
A disadvantage of the current `set_geometry` way in this PR, is that you either first need to have a GeoDataFrame that doesn't yet have a proper geometry column (kind of an invalid GeoDataFrame, something which I would like to see disallowed in the future), or either need to rely on the monkey-patched version of `set_geometry` of a plain DataFrame (although this could be solved more cleanly in the future using a DataFrame accessor).

**Comment by jorisvandenbossche** [comment]
@jdmcbr @ljwolf @martinfleis @poplarShift more comments or feedback on this?

**Comment by martinfleis** [comment]
I agree with @ljwolf's point of `Point`-specific API and with @jorisvandenbossche's notes about inferring. What I see as the cleanest solution is mentioned `from_xy` function. I don't see it as a problem that it would not drop x, y columns from dataframe, you can always do it manually if you wish to get rid of them (I'd prefer to keep them anyway in most of the cases). Then you are keeping `set_geometry` geom_type non-specific, while enhancing the conveniency of such a typical case.

**Comment by jorisvandenbossche** [comment]
OK, thanks all for the input! Let's go with that then. 
Any preference for `from_xy` or `points_from_xy` ?

@poplarShift (or somebody else) any interest in doing a PR for that? (I will otherwise do it somewhere next week I hope)

**Comment by martinfleis** [comment]
@jorisvandenbossche I'll give it a go.

**Comment by poplarShift** [comment]
Thanks for feedback everyone, sorry for my slow response. I'm very happy with the `from_xy` kind of approach if that fits better in the big picture! Thanks @martinfleis for putting something together.

**Comment by jorisvandenbossche** [comment]
Superseded by https://github.com/geopandas/geopandas/pull/896

**Pull request closed without merging**
