### PR TITLE
TST: skip postgis duplicate column test for pandas 2.0.x

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
See https://github.com/geopandas/geopandas/pull/2849#issuecomment-1537099850

### CODE REVIEW

**Review by martinfleis — APPROVED** [review]
Thanks!

**Comment by martinfleis** [comment]
Not entirely sure where the failure comes from.

**Comment by m-richards** [comment]
> Not entirely sure where the failure comes from.

Looking at the failures, it's like `PANDAS_GE_20` isn't set correctly, we're getting pandas 2 error messages but not hitting our compat blocks for them. Actually looking in more detail, the environment is still running against pip installed pandas 2.0.0rc which is probably not ideal. I'll push a commit bumping that and see what happens

**Comment by martinfleis** [comment]
Now it behaves as expected. Though we have `if grep SKIPPED >/dev/null;then echo "TESTS SKIPPED, FAILING" && exit 1` in the action for this part so it fails. Maybe we can use `xfail/xpass` instead here?

**Comment by jorisvandenbossche** [comment]
Ah, yes, thanks for the fixup!

**Comment by jorisvandenbossche** [comment]
Yes, and will make it xfail

**Pull request merged**
