### PR TITLE
Get include and library paths for GEOS from `shapely._buildcfg.get_os_config`

### PR DESCRIPTION
**Pull request by eriknw**
Hopefully this will allow `make inplace` to work for more people and under more circumstances.  This gets the paths with system calls to `geos-config`.  XREF #473

### CODE REVIEW

**Comment by mrocklin** [comment]
cc @jorisvandenbossche

**Comment by mrocklin** [comment]
Verified that this works well on my system where I have geos installed using the system package manager (apt-get)

**Comment by jdmcbr** [comment]
Also works for me (Ubuntu 17.04, geos installed with apt-get).

**Comment by jorisvandenbossche** [comment]
Works now for me as well, with conda-forge installed GEOS in an environment, so merging. @eriknw Thanks a lot!

**Pull request merged**
