### PR TITLE
CI: set up postgresql/postgis on Travis

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
#1389

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@brendan-ward thanks for the review! 

I fully agree the actual tests are also not in a good state, and can some improvement. But, I mainly want to "just" get the existing tests running for now, as there are other PRs that are doing changes to the postgis functionality, and would like to have a minimal testing enabled.

So I would like to leave further clean-up / improvement for a follow-up issue / PR. 

I quickly tried to add an actual `assert_geodataframe_equal` as you suggested, and with the current messy database table creation setup, this needs several workarounds to get it passing (the column names (converted to lower case, geometry colum name) and order, the crs, ..). So added several comments for things that can be further cleaned up.

**Comment by martinfleis** [comment]
Thank you @jorisvandenbossche! Drawing from the commit history, this wasn't straightforward PR :).

> So I would like to leave further clean-up / improvement for a follow-up issue / PR.

Fully agree.

**Comment by jorisvandenbossche** [comment]
It's mainly a slow feedback loop when trying things out on travis ... ;)

**Comment by jorisvandenbossche** [comment]
Reverted the `assert_frame_equal` for now, all kinds of side issues popped up, also with older dep versions (all worth solving of course!)

**Comment by martinfleis** [comment]
Let's open an issue for that, so we can fix that later.

**Comment by jorisvandenbossche** [comment]
Opened https://github.com/geopandas/geopandas/issues/1395 as follow-up to improve the tests

**Comment by martinfleis** [comment]
Thanks. I'll merge it to related PRs.

**Pull request merged**
