### PR TITLE
TST: Make port settable or gettable from env

### PR DESCRIPTION
**Pull request by jdmcbr**
As raised in #822, may be useful to have the postgis port settings more
generic.

### CODE REVIEW

**Comment by mazzma12** [comment]
Good starting point, I think that extending this to the full PG config would be the next step (host, user, passowrd, db name ...). Also, I would go for `PG_` suffix naming as it is seen quite often.

**Comment by jdmcbr** [comment]
Hmm, in my limited experience I've only seen `PGPORT`; more importantly, that's consistent with the docs: https://www.postgresql.org/docs/current/libpq-envars.html

Sure, added user, password, and host as well. This particular utility is intended for connecting to a test database that currently needs to be manually created for the tests to run (which, in retrospect, I certainly should have highlighted in your PR): https://github.com/geopandas/geopandas/blob/master/geopandas/tests/util.py#L124-L129

**Comment by mazzma12** [comment]
> Hmm, in my limited experience I've only seen `PGPORT`; more importantly, that's consistent with the docs: https://www.postgresql.org/docs/current/libpq-envars.html
Sure, my bad.

> Sure, added user, password, and host as well. This particular utility is intended for connecting to a test database that currently needs to be manually created for the tests to run (which, in retrospect, I certainly should have highlighted in your PR): https://github.com/geopandas/geopandas/blob/master/geopandas/tests/util.py#L124-L129

Thanks now I should be able to test is with PG running in docker without having to forward the socket :)

**Comment by jorisvandenbossche** [comment]
Sure, this is only for testing right? This seems certainly good to make testing locally easier to do.

**Comment by jorisvandenbossche** [comment]
@jdmcbr Can you maybe just add a module docstring mentioning this in the `test_sql` file?

**Pull request merged**
