### PR TITLE
updated the demo dataset

### PR DESCRIPTION
**Pull request by jessepisel**
fix for issue #804 
new shapefiles downloaded from http://www.naturalearthdata.com/downloads/110m-cultural-vectors/110m-admin-0-countries/

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@jessepisel Thanks for your contribution

The version we have currently included is a processed one: removed features, renamed columns, ... (to make it more usable for demonstration / example purposes). For example, the included dataset has only 6 columns, the one you included here 95. 

So what we ideally should do: write a small script that takes the original data, processes it and writes it again to a shapefile, and include this script in the repo so everybody (and we later) can reproduce this (we should have done this initially when we added the data ..) 
@jessepisel would you like to do this? (I don't think it should be too hard, it is mainly checking the data to find the matching 6 columns)

**Comment by jorisvandenbossche** [comment]
@jessepisel question: where is the download link coming from? I only see the zip downloads from http://www.naturalearthdata.com/downloads/110m-cultural-vectors/110m-admin-0-countries/ 
I am also asking because there is 'naturalearth-3.3.0' in there, so wondering if this is the latest version (which should be 4.1.0)

**Comment by jessepisel** [comment]
I was pulling the naturalearth-3.3.0 file from geojson.xyz as a geojson, then converting to a shapefile after dropping columns. I'll update so that it is pulling the 4.1.0 from the zip download.

**Comment by jdmcbr** [comment]
@jessepisel Thanks! I made a couple more slight adjustments per @jorisvandenbossche to get this done before a 0.5.0 release.

**Comment by jorisvandenbossche** [comment]
Thanks @jessepisel and @jdmcbr !

**Comment by martinfleis** [comment]
@jdmcbr This new demo dataset broke `test_legend` and `test_classification_kwds` as they were depending on the exact values of the old one. Since then all checks are failing. I can make a quick PR to fix that.

**Comment by jdmcbr** [comment]
@martinfleis Ah, so they are. I hadn't yet had a look at my PR from last night to see the build had failed on those tests. If you want to update those, that'd be great, otherwise I can put that in myself later today.

**Comment by martinfleis** [comment]
@jdmcbr updated in #891

**Comment by jorisvandenbossche** [comment]
Yeah, I also saw the failure, and was considering for a while whether we should rather keep the data intact (and only fixing the Antarctica shape (which was the original problem) keeping the attribute columns intact) or just update our tests. 
Other people might also rely on the exact values, but in the end, they are really more meant to be demo dataset and not to be relied upon for actual analyses (meaning, the exact values). So maybe simply updating is fine. Although, ideally, for a more full fledged data download system (which geopandas.datasets currently isn't) there would be some version support.

@martinfleis Thanks for noting it and making a PR!

**Pull request merged**
