### PR TITLE
DOC: fix RTD builds

### LINKED ISSUE #2124: BUG: readthedocs is failing
RTD is failing (for some time already) - https://readthedocs.org/projects/geopandas/builds/14797073/

I'll try to fix that later tonight.

### PR DESCRIPTION
**Pull request by martinfleis**
Let's start debugging #2124 . The error comes from `nbsphinx` and happened after changes to `scheme`. Commenting out all choropleth plots within Jupyter notebooks.

Closes #2124

### CODE REVIEW

**Comment by martinfleis** [comment]
Updating all packages to the latest (with the exception of pandas to avoid that regression) fixed the issue on my side. Geoplot works fine, geocoding as well. So that should fix rtd builds as well. If we won't hit the memory wall again.

**Comment by martinfleis** [comment]
We did - https://readthedocs.org/projects/geopandas/builds/14800173/

I have sent a request to RTD to switch geopandas to mamba. I am not sure if there's something we can do on our side to fix this.

**Comment by jorisvandenbossche** [comment]
Let's merge this anyway, it might be that we have less memory for PRs (the latest on master didn't have the memory problem)

**Comment by jorisvandenbossche** [comment]
Passed on master! https://readthedocs.org/projects/geopandas/builds/14802704/ Thanks!

**Pull request merged**
