### PR TITLE
ENH: explore() remove warning from mapclassify

### PR DESCRIPTION
**Pull request by rraymondgh**
use warnings context manager to suppress map classify warning when column is invariant

### CODE REVIEW

**Comment by martinfleis** [comment]
I guess that this should be suppressed in `mapclassify` rather than here, to make a proper fix. Would you mind trying to push a fix there? Or opening an issue at least?

**Comment by rraymondgh** [comment]
@martinfleis I'll take a look at cloning **mapclassify** and fixing there.  for now I'll leave this PR open

**Comment by martinfleis** [comment]
This was just fixed in the upstream PR https://github.com/pysal/mapclassify/pull/131

**Comment by jGaboardi** [comment]
@rraymondgh this has now been resolved upstream in pysal/mapclassify#129.

**Comment by jGaboardi** [comment]
@martinfleis you beat me to it!

**Pull request closed without merging**
