### PR TITLE
ENH: support using pyogrio in read_file / to_file with engine keyword

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
For https://github.com/geopandas/geopandas/issues/2217

Many of the tests are already passing!

- The tests reading from file like objects depends on https://github.com/geopandas/pyogrio/pull/25
- There are still some failures caused by int32 vs int64 in the resulting dataframe (I think that's because pyogrio is "honoring" the type in the file, we should see if we can add a keyword to `assert_geodataframe_equal` to be flexible here)
- Of course still needs more keyword handling, tests, docs, etc

One question is to what extent we want to "translate" our current keywords to pyogrio's, or rather pass-through kwargs as is. For example, currently, I am translating `rows` into `skip_features`/`max_features` for pyogrio.

cc @brendan-ward

### CODE REVIEW

**Review by brendan-ward — COMMENTED** [review]
Thanks for working on this @jorisvandenbossche !  Getting closer to faster I/O!

I gave this a quick look over and didn't see any major issues.  The aliasing of parameters to pyogrio parameters seems reasonable, but we can certainly consider changing those keywords in pyogrio if there's a good case for it.

There are likely several things that Fiona provides that we do not yet cover fully in pyogrio, so we should determine if there are any major ones preventing use here.  Others will likely become more clear as users start using the pyogrio engine.

Just opened [issue to decide about geometry filter](https://github.com/geopandas/pyogrio/issues/32) since that is something provided by Fiona not yet in pyogrio.  Depending on that, we may want to block use of the `mask` keyword when using the pyogrio engine, or use the bbox filter in pyogrio followed by intersects predicate here.

The other issues documented so far ([uri schemes](https://github.com/geopandas/pyogrio/issues/21), [write empty GeoDataFrames](https://github.com/geopandas/pyogrio/issues/27)) seem more about minor improvements rather than blockers.

**Comment by jorisvandenbossche** [comment]
One additional thing is that we currently rely on fiona in some of the common logic in `read_file` to detect zip files:

https://github.com/geopandas/geopandas/blob/4a972f059c936ca71c38d3ae5c6c6a744b7bf152/geopandas/io/file.py#L179-L197

We should probably refactor that to do ourselves, or otherwise move into the fiona vs pyogrio specific parts.

**Comment by jorisvandenbossche** [comment]
Unless we would like to add this functionality to pyogrio.read_dataframe? (the ability to read a zip file from a path without having the `zip://` or `/vsizip/`)

**Comment by jorisvandenbossche** [comment]
Hmm, and now the macos build is failing, because of a pyarrow import error. But it seems that for some reason it installed a few packages from defaults instead of conda-forge, which probably explains it (so not actually related to pyogrio, just because of changing the env a bit)

**Comment by jorisvandenbossche** [comment]
This is finally passing! Merging then

**Comment by brendan-ward** [comment]
Thanks for all the work here @jorisvandenbossche !  🚀

**Pull request merged**
