### PR TITLE
Add changelog for v0.2.0

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Started with a small overview of changes for 0.2

### CODE REVIEW

**Comment by nickeubank** [comment]
Great. Either here or after commit, need to add:

- `overlay`
- `sjoin`
- `dissolve` (if that gets integrated)
- embedded data

**Comment by jorisvandenbossche** [comment]
I added some more

Only not sure about the following:

* Coordinate indexer ? #55
* Spatial index (``_sindex``)  #141

**Comment by jorisvandenbossche** [comment]
@kjordahl What do you think about this?

**Comment by nickeubank** [comment]
@jorisvandenbossche 

- added example data
- updated docs (people who get this via email won't know web page is now very different)

Bugs: 
- #306

**Comment by jorisvandenbossche** [comment]
@nickeubank example data are already included (last item in the improvements list), and the updated docs are also mentioned (first item). If we sent an announcement email, we should indeed add a link to the most recent docs.

I didn't mention that bug because it was in a feature that is new (so it is not a bug fixed in previous release), just to limit the list. I didn't mention some others like that as well.

**Comment by nickeubank** [comment]
Sounds good!

**Comment by kjordahl** [comment]
@jorisvandenbossche 👍 

Yes, we should have the spatial index and `.cx` attribute slicing as well. The latter isn't really documented at all, either. For the changelog, can you just add a line for each of these?

**Comment by jorisvandenbossche** [comment]
@kjordahl added an entry for both

**Pull request merged**
