### PR TITLE
REF: rename GeometryArray.data to _data

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
As a first step, this makes the `.data` attribute of GeometryArray into a read-only property, and switches to use `_data` internally. In a next step we can then add a deprecation warning to the public property.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
FWIW, the matplotlib failures in the dev build are known and the change might be reverted on the matplotlib side: https://github.com/matplotlib/matplotlib/issues/25162 (and if not, it's also easy to solve with adding some `squeeze()` calls to remove the extra dimension of length 1 in the color array.

**Comment by martinfleis** [comment]
Two more cases to change (unless we suppress deprecation warnings there, once we have them):

Here
https://github.com/geopandas/geopandas/blob/ed20d113d58f23dd5f564c7347a3883aa248e84a/geopandas/tests/test_sindex.py#L439

And two cases here

https://github.com/geopandas/geopandas/blob/ed20d113d58f23dd5f564c7347a3883aa248e84a/geopandas/tests/test_sindex.py#L644-L648

Those are the only places that pop up when I add `raise`  to `data`.

Also - shall we add a specific test for this?

**Comment by m-richards** [comment]
> FWIW, the matplotlib failures in the dev build are known and the change might be reverted on the matplotlib side: [matplotlib/matplotlib#25162](https://github.com/matplotlib/matplotlib/issues/25162) (and if not, it's also easy to solve with adding some `squeeze()` calls to remove the extra dimension of length 1 in the color array.

Thanks for working this out, I had a look earlier but couldn't tell if this was deliberate or a bug, nice to now know.

**Review by m-richards — COMMENTED** [review]
This all looks fine, I just missed the memo on the rationale for the change, is this somehow related to #2769, or there another reason for doing this?

**Comment by jorisvandenbossche** [comment]
Sorry for not providing much context. This is rather related to https://github.com/geopandas/geopandas/issues/2691 (PyGEOS -> Shapely migration). By making `.data` a property (instead of just a simple attribute), we can add warnings in a next step (specifically warning that those pygeos geometries will become shapely geometries in the future, when we switch to prefer shapely above pygeos; and maybe generally deprecating accessing `.data` directly in favor of `np.asarray(..)` or `.to_numpy()`, to avoid exposing "internal" implementation details)

**Pull request merged**
