### PR TITLE
BLD: enable to build for Python 2.7 on Windows (vc9)

### PR DESCRIPTION
**Pull request by ocefpaf**
Continuing #618

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
I suppose that the stdbool.h could be solved as well directly in the .c file were it is used (https://github.com/geopandas/geopandas/blob/1c62492eebd89bada9312a6d2cdb28fdfe91c2ff/geopandas/algos.c#L7)

And I suppose the remaining build error has to do with the algos.c use of STRTree:

```
C:\Users\appveyor\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Igeopandas -IC:\Miniconda-x64\envs\test-environment\lib\site-packages\numpy\core\include -IC:\Miniconda-x64\envs\test-environment\\Library\\include -IC:\Miniconda-x64\envs\test-environment\include -IC:\Miniconda-x64\envs\test-environment\PC /Tcgeopandas/algos.c /Fobuild\temp.win-amd64-2.7\Release\geopandas/algos.obj
algos.c
geopandas/algos.c(68) : error C2275: 'GEOSSTRtree' : illegal use of this type as an expression
        C:\Miniconda-x64\envs\test-environment\\Library\\include\geos_c.h(123) : see declaration of 'GEOSSTRtree'
geopandas/algos.c(68) : error C2065: 'tree' : undeclared identifier
geopandas/algos.c(81) : error C2065: 'tree' : undeclared identifier
geopandas/algos.c(81) : warning C4047: 'function' : 'GEOSSTRtree *' differs in levels of indirection from 'int'
geopandas/algos.c(81) : warning C4024: 'GEOSSTRtree_query_r' : different types for formal and actual parameter 2
geopandas/algos.c(86) : warning C4090: '=' : different 'const' qualifiers
geopandas/algos.c(109) : error C2065: 'tree' : undeclared identifier
geopandas/algos.c(109) : warning C4047: 'function' : 'GEOSSTRtree *' differs in levels of indirection from 'int'
geopandas/algos.c(109) : warning C4024: 'GEOSSTRtree_destroy_r' : different types for formal and actual parameter 2
```

cc @mrocklin

**Comment by mrocklin** [comment]
geopandas/algos.c(68) : error C2275: 'GEOSSTRtree' : illegal use of this type as an expression
            C:\Miniconda-x64\envs\test-environment\\Library\\include\geos_c.h(123) : see declaration of 'GEOSSTRtree'

I'm not sure exactly what's causing this.  If this were a very old C implementation then I might declare tree in the first few lines of this function.  I'm not sure what else might be wrong.

FWIW we're also planning, at some point, to replace the use of STRTree with libspatialindex (or at least investigate this replacement) so this problem might disappear in the moderate-future.

**Comment by mrocklin** [comment]
Ah, I see now that @jorisvandenbossche has already done this.

**Comment by jorisvandenbossche** [comment]
Yes, it turned out to be a simple fix, just that on python 2 on windows and older C compiler is used, which is a bit more strict on where declarations are placed: https://stackoverflow.com/a/9903698/653364

**Comment by ocefpaf** [comment]
> Yes, it turned out to be a simple fix, just that on python 2 on windows and older C compiler is used, which is a bit more strict on where declarations are placed: https://stackoverflow.com/a/9903698/653364

Nothing is simple when it comes to compiling stuff on Windows IMO :smile: 

But I am glad Python 2.7 will see `geopandas` with cython before 2020 :wink: 

Should we remove the allow_failure line?

**Comment by jorisvandenbossche** [comment]
Yes, removed the allow_failures.

For the stdbool.h, it seems a bit cleaner of we could fix this in the actual code instead of the external `appveyor/stdbool.h` file (eg also someone wanting to build it locally on windows will need to copy that file to an include directory). 
Can I just put the 

```
typedef int bool;
#define false 0
#define true 1
```

inside algos.c directly? Or is this not desired for when the file is built on linux?

**Comment by ocefpaf** [comment]
> Or is this not desired for when the file is built on linux?

I think that is OK. I go for the external file when packaging b/c that is a common "error" when compiling extensions and most devs are not interested into incorporating that.

**Comment by jorisvandenbossche** [comment]
Merging this (we can always move the patch to the code itself later if someone asks for this).

Then we update conda-forge as well!

**Pull request merged**
