### PR TITLE
ENH: use pyproj.CRS when possible

### PR DESCRIPTION
**Pull request by snowman2**
Needs tests for new version & probably needs current tests fixed.
Much to do here, but it is a start.

### CODE REVIEW

**Comment by snowman2** [comment]
Likely will address *but remains to be seen):
#943
#245
#65
#923

**Comment by snowman2** [comment]
Lots of pyproj version checking going on. Would you prefer to just pin pyproj>=2.2.0?

**Comment by snowman2** [comment]
One issue I see is that PROJ does not consider `epsg:4326` and `+init=epsg:4326` to be equal, whereas `fiona` does:
```
>>> crs_wkt = 'GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]]'
>>> cc1 = CRS(crs_wkt)
>>> cc1
<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- undefined
Datum: World Geodetic System 1984
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

>>> cc2 = CRS("+init=epsg:4326 +type=crs")
>>> cc2
<Geographic 2D CRS: +init=epsg:4326 +type=crs>
Name: WGS 84
Axis Info [ellipsoidal]:
- lon[east]: Longitude (degree)
- lat[north]: Latitude (degree)
Area of Use:
- name: World
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich
```
The difference is subtle, but it is mostly the difference between the axis being geodetic or not.
This is an issue when writing to a file and reading in the projection back in.

**Comment by jorisvandenbossche** [comment]
@snowman2 Thanks a lot for starting this!

I opened https://github.com/geopandas/geopandas/issues/1003 for some of the more general discussion points. Will try to give more detailed code feedback here later.

**Comment by snowman2** [comment]
Not sure where it is coming from but I don't see `epsg:26018` on any google search or on:
http://epsg.io/?q=26018.
And it seems PROJ does not recognize it either and is causing tests to fail.

**Comment by snowman2** [comment]
Using pyproj 2.2.0 (current master):
image

**Comment by snowman2** [comment]
I came up with a version that returns a dictionary. Only one test on Travis failed due to precision on python 2. The changes are on a separate commit and can be easily removed depending on the direction you would like to proceed in. If you like the dict option, I can fix that python 2 test to require less precision when testing the difference.

**Comment by snowman2** [comment]
Closing for prefer to #1101

**Pull request closed without merging**
