### PR TITLE
BUG/COMPAT: fix fillna by filling with Polygon instead of Point

### LINKED ISSUE #509: BUG/COMPAT: missing values handling / fillna no longer working with shapely 1.6
See https://github.com/Toblerity/Shapely/issues/510 for more detailed exploration of the problem

Temporarily pinned our CI to older shapely version (but kept one with the latest shapely in the allowed failures section) in https://github.com/geopandas/geopandas/pull/508

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
This should for now close #509 (although I am not really satisfied with the fix -> still relies on the fact that the array interface for Polygon won't change).

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
I only don't know shapely enough to know whether BaseGeometry is meant to be used like that ..

**Comment by jorisvandenbossche** [comment]
@jdmcbr I am thinking about merging this one as is? As I think it should work now with the polygon as well, and I don't feel sure about using the BaseGeometry

**Comment by jdmcbr** [comment]
@jorisvandenbossche That's fine with me. If we hear from @sgilles that using `BaseGeometry` instead would be a better way to go long term, we can switch it later. It certainly doesn't seem like something that should gate release, and this is the last remaining issue we're targeting, right?

**Comment by sgillies** [comment]
As I said in the Shapely tracker, I'm :+1: on using `BaseGeometry`. A derived `Empty` class could be better.

**Comment by jorisvandenbossche** [comment]
OK, pushed to update that!

I will comment about the Empty class on the shapely issue (as there are some things about empty geoms that confuse me, you can have empty points, polygons, etc, and they seem to be the same in some sense (same type, same repr), but behave different in other parts). 
But it can take a while (am on EuroScipy now, and first want to get geopandas released)

**Pull request merged**
