### PR TITLE
Do not densify geometries in __setitem__

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Closes https://github.com/geopandas/geopandas/issues/528

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@jreback Currently I use the following code to replace one block in a BlockManager with a new one:

```
            if key not in self.columns:
                self[key] = 1

            key_loc = self.columns.get_loc(key)
            block_loc = self._data._blknos[key_loc]

            columns, index = self._data.axes
            blocks = self._data.blocks
            blocks = list(blocks)

            orig_geom_block = blocks[block_loc]
            new_geom_block = GeometryBlock(value, orig_geom_block.mgr_locs.as_slice)
            blocks[block_loc] = new_geom_block

            block_manager = BlockManager(blocks, [columns, index])
            self._data = block_manager
```

Do you know of any better way?

**Comment by jreback** [comment]
is there a reason you are not using BlockManager.insert?

**Comment by jorisvandenbossche** [comment]
For the same reason I did all the recent PRs related to the internals: that takes 'values' and not a block, and recreates the block based on those values. 
I could check in pandas if I could change BlockManager.set/insert to also take blocks, and if that is passed to not recreate the block. But with the current master of pandas, I don't see an easier way to do this as done in this PR.

**Comment by jorisvandenbossche** [comment]
cc @mrocklin any comments here ?

**Comment by mrocklin** [comment]
My apologies for the silence here.  This was buried in my e-mail.

**Comment by jorisvandenbossche** [comment]
No problem! (and after merging feedback always welcome, even if it is to make the code / comments clearer, as this is rather internals black magic. It might be good to move all code that deals with block manager internals to a couple of helper functions)

**Pull request merged**
