### PR TITLE
Replace pyproj with fiona.transform

### PR DESCRIPTION
**Pull request by micahcochran**
This is experimental for the moment.  It is more to start a discussion.  It is regarding #315.

I don't even know if this is a good idea.

A benchmark would be nice to show if there is a performance difference.  In very limited testing, I found fiona.transform to be a bit faster.

My branch had one test fail.

### CODE REVIEW

**Comment by jdmcbr** [comment]
@micahcochran I just tested this out. I didn't see any performance improvement as compared to master, with the version on this branch a bit slower, though the difference is fairly slight, in any case. It seems like the primary motivation here is removing a dependency? Is there any other benefit this would provide?

Benchmark results:
```
· Running 2 total benchmarks (2 commits * 1 environments * 1 benchmarks)
[  0.00%] · For geopandas commit hash 1ddb5184:
[  0.00%] ·· Building for virtualenv-py3.6-cython-descartes-fiona-matplotlib-pandas-pyproj-rtree-shapely-six.
[  0.00%] ·· Benchmarking virtualenv-py3.6-cython-descartes-fiona-matplotlib-pandas-pyproj-rtree-shapely-six
[ 50.00%] ··· Running transform.Boroughs.time_transform_wgs84              1.13s
[ 50.00%] · For geopandas commit hash c322b54c:
[ 50.00%] ·· Building for virtualenv-py3.6-cython-descartes-fiona-matplotlib-pandas-pyproj-rtree-shapely-six.
[ 50.00%] ·· Benchmarking virtualenv-py3.6-cython-descartes-fiona-matplotlib-pandas-pyproj-rtree-shapely-six
[100.00%] ··· Running transform.Boroughs.time_transform_wgs84           926.68ms
```

**Comment by micahcochran** [comment]
> It seems like the primary motivation here is removing a dependency?
Yes

> Is there any other benefit this would provide?
No

**Comment by jdmcbr** [comment]
Per @jorisvandenbossche suggestion, added another benchmark for a frame with many points, rather than a few rows with detailed polygons. The performance differences are considerable for this case. @micahcochran What sort of cases were you seeing a performance gain in using `fiona` rather than `pyproj`?

```
· Running 4 total benchmarks (2 commits * 1 environments * 2 benchmarks)
[  0.00%] · For geopandas commit hash 1ddb5184:
[  0.00%] ·· Building for virtualenv-py3.6-cython-descartes-fiona-matplotlib-pandas-pyproj-rtree-shapely-six.
[  0.00%] ·· Benchmarking virtualenv-py3.6-cython-descartes-fiona-matplotlib-pandas-pyproj-rtree-shapely-six
[ 25.00%] ··· Running transform.CRS.time_transform_many_points             4.47s
[ 50.00%] ··· Running transform.CRS.time_transform_wgs84                   1.17s
[ 50.00%] · For geopandas commit hash c322b54c:
[ 50.00%] ·· Building for virtualenv-py3.6-cython-descartes-fiona-matplotlib-pandas-pyproj-rtree-shapely-six.
[ 50.00%] ·· Benchmarking virtualenv-py3.6-cython-descartes-fiona-matplotlib-pandas-pyproj-rtree-shapely-six
[ 75.00%] ··· Running transform.CRS.time_transform_many_points          759.17ms
[100.00%] ··· Running transform.CRS.time_transform_wgs84                972.05ms
```

**Comment by jdmcbr** [comment]
@micahcochran Are you opposed to closing this, given the benchmark results?

**Pull request closed without merging**
