### PR TITLE
CLN: Use generators inplace of lists

### PR DESCRIPTION
**Pull request by pratapvardhan**
A minor refactoring to use generators instead of lists in built-in Python functions. Please feel free to reject this, if it's unnecessary.

### CODE REVIEW

**Comment by micahcochran** [comment]
`_version.py` looks like it was generated with [python-versioneer](https://github.com/warner/python-versioneer).   I think you should try to update that code within that project.  Then, this project could regenerate `_version.py` using that.

Sidenote: `_version.py` was generated using version 0.16, but version 0.18 has been released.

**Comment by pratapvardhan** [comment]
Ugh, fair point. I'll revert `_version.py` change. That'll leave just the plotting example, would that be needed or should I close this?

**Comment by jorisvandenbossche** [comment]
The plotting one is still welcome!

**Comment by pratapvardhan** [comment]
Changes are done, this is good now.

**Comment by jorisvandenbossche** [comment]
Thanks!

**Pull request merged**
