### PR TITLE
Remove Stamen references from  plotting_basemap_background.ipynb

### PR DESCRIPTION
**Pull request by wboykinm**
Addressing https://github.com/geopandas/geopandas/issues/3065

### CODE REVIEW

**Review by martinfleis — COMMENTED** [review]
Thanks!

The default style is not OSM Mapnik but `OpenStreetMap HOT`. If you could change that then we're ready to merge.

**Comment by martinfleis** [comment]
Actually, could you maybe use CartoDB Positron tiles rather than DarkMatter? I think it will look better.

**Comment by martinfleis** [comment]
Can you use the "OpenStreetMap HOT" string instead of HOTOSM? The former resolvers to tiles, the latter will not.

**Comment by wboykinm** [comment]
@martinfleis It should be all set there.

**Review by martinfleis — APPROVED** [review]

**Comment by martinfleis** [comment]
Thanks!

**Pull request merged**
