### PR TITLE
BUG: assign Crimea to Ukraine in naturalearth_lowres

### LINKED ISSUE #2382: BUG: The dataset contains a mistake. Crimea should belong to Ukraine
- [+] I have checked that this issue has not already been reported.

- [+] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here

import pandas as pd
import geopandas

data = geopandas.read_file(geopandas.datasets.get_path('naturalearth_lowres'))

ukraine = data.loc[data['name'] == 'Ukraine']
ukraine.plot()
```

#### Problem description

Plotting map of Ukraine.
Crimea isn't displayed, despite being a part of Ukraine. It is annexed indeed, but it is a temporary issue, that is going to be resolved 
soon. No self-respecting countries recognized Crimea's seperation. So it should be considered a part of Ukraine, obviously.

#### Expected Output
The map should show Crimea.
#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.7.12 (default, Jan 15 2022, 18:48:18)  [GCC 7.5.0]
executable : /usr/bin/python3
machine    : Linux-5.4.144+-x86_64-with-Ubuntu-18.04-bionic

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.6.2
GEOS lib   : /usr/lib/x86_64-linux-gnu/libgeos_c.so
GDAL       : 3.4.1
GDAL data dir: /usr/local/lib/python3.7/dist-packages/fiona/gdal_data
PROJ       : 8.1.1
PROJ data dir: /usr/local/lib/python3.7/dist-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.10.2
pandas     : 1.3.5
fiona      : 1.8.21
numpy      : 1.21.5
shapely    : 1.8.1.post1
rtree      : None
pyproj     : 3.2.1
matplotlib : 3.2.2
mapclassify: None
geopy      : 1.17.0
psycopg2   : 2.7.6.1 (dt dec pq3 ext lo64)
geoalchemy2: None
pyarrow    : 6.0.1
pygeos     : None
/usr/local/lib/python3.7/dist-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)

</details>

### PR DESCRIPTION
**Pull request by martinfleis**
Fixes #2382

This is an immediate patch of the `naturalearth_lowres` dataset included in GeoPandas. The current version shipped by the provider unfortunately include Crimea as a part of Russia due to their [de facto](https://www.naturalearthdata.com/about/disputed-boundaries-policy/) policy.

This PR overrides that and assigns the peninsula back to Ukraine.

This PR is considered a bug fix and is targeted for the next patch release 0.12.2 that is due most likely by the end of today.

However, this is a temporary solution until the complex approach towards _disputed regions_ and their treatment in GeoPandas is properly discussed and solved. While the exact solution is unsure as of now, due to some concerns regarding the latest proposal raised by the community on Github, twitter and mastodon, we can assure that as long as this projects ships a world map with political boundaries, Crimea will be part of Ukraine.

I want to, once again, deeply apologise to the GeoPandas community and everyone affected within and outside of Ukraine for our slow response and initial reluctancy.

### CODE REVIEW

**Comment by budnik** [comment]
Thanks for the prompt fix. The people of Ukraine do appreciate it.

**Comment by martinfleis** [comment]
The map can be verified here (very bottom) https://geopandas--2670.org.readthedocs.build/en/2670/docs/user_guide/interactive_mapping.html

**Review by jorisvandenbossche — APPROVED** [review]
Looks good, also verified it locally it is working and the new geometries look correctly modified.

The cities dataset should in principle not have changed?

**Comment by martinfleis** [comment]
> The cities dataset should in principle not have changed?

I ran the whole creation script so it probably just picked a new patch release. Can remove that if you prefer that.

**Comment by lwasser** [comment]
@martinfleis thank you and the other geopandas maintainers for the quick response on this. i am grateful for the huge effort that you put into maintaining geopandas!

**Pull request merged**
