### PR TITLE
BUG: return empty gdf for empty result of clip

### PR DESCRIPTION
**Pull request by rwijtvliet**
Bugfix and tests for https://github.com/geopandas/geopandas/issues/1363

Please review and comment if possible; I'm new to this

### CODE REVIEW

**Comment by martinfleis** [comment]
Thank you! This looks good and in line with existing behaviour. I am just thinking, looking at it, that it might be better to do empty slice of `gdf` instead of rebuilding it like this. Because now we lose the information on active geometry column and after #1339 also the information on the CRS of other columns. So instead of doing

```py
return (
             GeoDataFrame(columns=gdf.columns, crs=gdf.crs)
             if isinstance(gdf, GeoDataFrame)
             else GeoSeries(crs=gdf.crs)
         )
```

we may do 
```py
return gdf.iloc[:0]
```
which will work for GeoSeries as well as GeoDataFrame. That applies for both checks actually. What do you think?

**Comment by rwijtvliet** [comment]
Ah that's a great concise way of writing it, looks good to me.

**Comment by rwijtvliet** [comment]
Btw, could I have prechecked my code? So that it wouldn't have embarrassingly failed here? ;) I ran `pytest geopandas/tools/tests/test_clip.py` and it gave me the all OK.

**Comment by martinfleis** [comment]
> Btw, could I have prechecked my code? So that it wouldn't have embarrassingly failed here?

The current failure is not related to this PR (#1360). However, your commit initially failed due to style (https://travis-ci.org/github/geopandas/geopandas/jobs/673519137#L3036). We are [using black](https://geopandas.readthedocs.io/en/latest/contributing.html#style-guide-linting) and check for that. You could have [blacken](https://black.readthedocs.io/en/stable/) your code before.

We can ignore current fails and merge this.

**Comment by martinfleis** [comment]
Thank you @rwijtvliet!

**Pull request merged**
