### PR TITLE
Add NYC borough boundaries as included dataset

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Closes https://github.com/geopandas/geopandas/issues/295, closes https://github.com/geopandas/geopandas/issues/368

xref https://github.com/geopandas/geopandas/pull/373

To avoid changing geometries or changing download links with future updates, and to have the dataset more easily available as example dataset, I included the zip file in the source and made it available through `geopandas.datasets`

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@micahcochran I included the copy you added to github (https://github.com/geopandas/geopandas/issues/368#issuecomment-256641732) in the actual source code. I don't find anything about the actual license terms on redistributing of the open data of NYC gov. But normally the notion of open data includes freedom to redistribute (https://en.wikipedia.org/wiki/Open_data#Overview), so I assume this is OK.

**Comment by jorisvandenbossche** [comment]
Although we should probably best add a source acknowledgement to them somewhere. Not sure where best to place this.

**Comment by micahcochran** [comment]
I'd suggest a new LICENSE_data file in the root directory.  You'd put licensing information for any data sets that are included in this file, so naturalearth_cities and the nybb.

Here's what the metadata in the nybb_16a.shp.xml file says...

### Summary

These districts were created by the Department of City Planning to aid city agencies in administering public services.

### Description

The borough boundaries of New York City clipped to the shoreline at mean high tide.

### Credits

Department of City Planning.

### Use limitations

This dataset is being provided by the Department of City Planning (DCP) on DCP’s website for informational purposes only. DCP does not warranty the completeness, accuracy, content, or fitness for any particular purpose or use of the dataset, nor are any such warranties to be implied or inferred with respect to the dataset as furnished on the website. DCP and the City are not liable for any deficiencies in the completeness, accuracy, content, or fitness for any particular purpose or use the dataset, or applications utilizing the dataset, provided by any third party.

**Comment by jorisvandenbossche** [comment]
@micahcochran added the explanation to the README for now, we can always later expand it.

**Pull request merged**
