### PR TITLE
TST: update groupby metadata test for pandas 2.1

### PR DESCRIPTION
**Pull request by m-richards**

### CODE REVIEW

**Review by martinfleis — APPROVED** [review]
This looks fine to me!

**Comment by jorisvandenbossche** [comment]
Thanks! 
I think `geopandas/tools/tests/test_sjoin.py::TestNearest::test_sjoin_nearest_exclusive[None-expected0]` will need a similar change?

**Comment by m-richards** [comment]
I think this now works, final dev failures are just astype and the EA null dtype tests

**Review by jorisvandenbossche — APPROVED** [review]

**Comment by jorisvandenbossche** [comment]
Thanks!

**Pull request merged**
