### PR TITLE
Start adding an asv benchmark suite

### PR DESCRIPTION
**Pull request by jorisvandenbossche**

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@mrocklin I did a comparison of current master (before) with latest geopandas-cython branch (after) (due to the coloring here on github red=good, green=bad):

```patch
All benchmarks:

       before           after         ratio
     [d57f51a7]       [224db013]
-          10.9ms           4.29ms     0.40  geom_methods.Bench.time_binary_float('distance')
-          17.0ms           2.04ms     0.12  geom_methods.Bench.time_binary_float_vector('distance')
-           179ms           61.6ms     0.34  geom_methods.Bench.time_binary_geo('difference')
-           146ms           97.8ms     0.67  geom_methods.Bench.time_binary_geo('intersection')
-           104ms           34.9ms     0.33  geom_methods.Bench.time_binary_geo('symmetric_difference')
            131ms            127ms     0.97  geom_methods.Bench.time_binary_geo('union')
-          85.6ms           45.7ms     0.53  geom_methods.Bench.time_binary_geo_vector('difference')
-          85.8ms           50.3ms     0.59  geom_methods.Bench.time_binary_geo_vector('intersection')
-          76.9ms           46.0ms     0.60  geom_methods.Bench.time_binary_geo_vector('symmetric_difference')
-          84.7ms           48.8ms     0.58  geom_methods.Bench.time_binary_geo_vector('union')
-          5.90ms            366μs     0.06  geom_methods.Bench.time_binary_predicate('contains')
           31.4ms           31.7ms     1.01  geom_methods.Bench.time_binary_predicate('crosses')
-          31.0ms           23.4ms     0.75  geom_methods.Bench.time_binary_predicate('disjoint')
-          7.81ms            225μs     0.03  geom_methods.Bench.time_binary_predicate('geom_almost_equals')
-          8.60ms            133μs     0.02  geom_methods.Bench.time_binary_predicate('geom_equals')
-          29.0ms           2.74ms     0.09  geom_methods.Bench.time_binary_predicate('intersects')
-          44.2ms           24.1ms     0.54  geom_methods.Bench.time_binary_predicate('overlaps')
-          34.9ms           16.0ms     0.46  geom_methods.Bench.time_binary_predicate('touches')
-          11.2ms            343μs     0.03  geom_methods.Bench.time_binary_predicate('within')
-          52.8ms           29.9ms     0.57  geom_methods.Bench.time_binary_predicate_vector('contains')
-          54.1ms           29.8ms     0.55  geom_methods.Bench.time_binary_predicate_vector('crosses')
-          53.6ms           30.4ms     0.57  geom_methods.Bench.time_binary_predicate_vector('disjoint')
-          17.9ms           1.48ms     0.08  geom_methods.Bench.time_binary_predicate_vector('geom_almost_equals')
-          55.3ms           29.7ms     0.54  geom_methods.Bench.time_binary_predicate_vector('geom_equals')
-          59.1ms           30.2ms     0.51  geom_methods.Bench.time_binary_predicate_vector('intersects')
-          80.8ms           32.7ms     0.40  geom_methods.Bench.time_binary_predicate_vector('overlaps')
-          52.1ms           30.0ms     0.58  geom_methods.Bench.time_binary_predicate_vector('touches')
-          55.4ms           31.9ms     0.58  geom_methods.Bench.time_binary_predicate_vector('within')
+          48.3ms            137ms     2.83  geom_methods.Bench.time_bounds
-           6.67s            3.34s     0.50  geom_methods.Bench.time_buffer
-          17.2ms            600μs     0.03  geom_methods.Bench.time_geom_type
-          35.4ms            706μs     0.02  geom_methods.Bench.time_unary_float('area')
-          36.0ms            723μs     0.02  geom_methods.Bench.time_unary_float('length')
-          12.0ms            440μs     0.04  geom_methods.Bench.time_unary_geo('boundary')
-          12.8ms            985μs     0.08  geom_methods.Bench.time_unary_geo('centroid')
-          13.5ms           1.52ms     0.11  geom_methods.Bench.time_unary_geo('convex_hull')
-          15.6ms            863μs     0.06  geom_methods.Bench.time_unary_geo('envelope')
+          8.24ms            123ms    14.95  geom_methods.Bench.time_unary_geo('exterior')
+          7.62ms            108ms    14.14  geom_methods.Bench.time_unary_geo('interiors')
           98.9ms           94.7ms     0.96  geom_methods.Bench.time_unary_geo_representative_point
-          3.25ms            130μs     0.04  geom_methods.Bench.time_unary_predicate('is_empty')
-          11.3ms            192μs     0.02  geom_methods.Bench.time_unary_predicate('is_ring')
-          2.73ms            120μs     0.04  geom_methods.Bench.time_unary_predicate('is_simple')
-          33.9ms           20.8ms     0.61  geom_methods.Bench.time_unary_predicate('is_valid')
            330ms            336ms     1.02  geom_methods.Bench.time_unary_union
            11.4s              n/a      n/a  overlay.Bench.time_overlay('difference')
            16.3s              n/a      n/a  overlay.Bench.time_overlay('identity')
            15.5s              n/a      n/a  overlay.Bench.time_overlay('intersection')
            15.1s              n/a      n/a  overlay.Bench.time_overlay('symmetric_difference')
            18.8s              n/a      n/a  overlay.Bench.time_overlay('union')
+           13.0s            16.5s     1.26  overlay.Countries.time_overlay('difference')
+           15.7s            20.2s     1.29  overlay.Countries.time_overlay('identity')
+           15.0s            21.4s     1.43  overlay.Countries.time_overlay('intersection')
+           13.3s            17.4s     1.31  overlay.Countries.time_overlay('symmetric_difference')
+           18.1s            23.4s     1.29  overlay.Countries.time_overlay('union')
+      22.5±0.5ms         31.8±1ms     1.42  overlay.Small.time_overlay('difference')
+        35.5±4ms         46.2±2ms     1.30  overlay.Small.time_overlay('identity')
         22.2±2ms         33.4±2ms    ~1.50  overlay.Small.time_overlay('intersection')
+      29.1±0.6ms         44.9±6ms     1.54  overlay.Small.time_overlay('symmetric_difference')
+      35.4±0.6ms         44.3±3ms     1.25  overlay.Small.time_overlay('union')
!             n/a           failed      n/a  plotting.Bench.time_plot_series
+      72.7±0.6ms         90.8±3ms     1.25  plotting.Bench.time_plot_series('LineString')
          126±1ms          132±8ms     1.04  plotting.Bench.time_plot_series('MultiPolygon')
+         102±1ms          357±2ms     3.50  plotting.Bench.time_plot_series('Point')
+         176±3ms         222±10ms     1.26  plotting.Bench.time_plot_series('Polygon')
!         107±1ms           failed      n/a  plotting.Bench.time_plot_series('mixed')
!             n/a           failed      n/a  plotting.Bench.time_plot_values
+      55.0±0.6ms         67.2±5ms     1.22  plotting.Bench.time_plot_values('LineString')
          100±6ms         89.6±3ms    ~0.90  plotting.Bench.time_plot_values('MultiPolygon')
+      98.9±0.7ms          270±4ms     2.73  plotting.Bench.time_plot_values('Point')
+       108±0.9ms          122±2ms     1.13  plotting.Bench.time_plot_values('Polygon')
!        76.6±1ms           failed      n/a  plotting.Bench.time_plot_values('mixed')
!           19.7s           failed      n/a  sjoin.Bench.time_sjoin('contains')
!           19.3s           failed      n/a  sjoin.Bench.time_sjoin('intersects')
!           17.1s           failed      n/a  sjoin.Bench.time_sjoin('within')
```

So some things have very good improvements (like area, within, intersects, ..), others only more modest (eg intersects with vector-vector). Not sure how reliable these are (or if there is a big variation on it) 

Some are much slower (eg exterior, interiors). I suppose this is because those are not yet cythonized, and now need a densification (btw, we should maybe think about caching the densified geometries?) 
Some of the plotting benchmarks are also slower, but again I think this is because they are not yet making use of the new capabilities, and therefore result in densification.

**Comment by mrocklin** [comment]
This is a very useful table.  I'll use this to organize future efforts.  Do you also have a sense for which of the currently-slower operations are commonly used?

**Comment by mrocklin** [comment]
OK, so how much do we care about bounds?  It doesn't actually correspond to any GEOS operation.  Previously it was used for the spatial index operations, but this is no longer necessary if we continue to use the GEOS spatial index rather than libspatialindex.

**Comment by jorisvandenbossche** [comment]
For my own work I mainly used intersects/intersection/buffer/distance/area/length, but not sure how typical that is. Would be good to get some real world feedback on this.

I indeed think that bounds is not that important for now. Although total_bounds is probably sometimes useful, and depends on that.

Plotting is also important, but I think those can make better use of the new. Eg for plotting points it still uses `x = [p.x for p in geoms]` while that is something already vectorized (I am looking at cleaning this up currently). 
For plotting lines and polygons, it would be useful to have functionality to get an array of the coordinates. Currently for linestrings, it loops over the geoms and gets is using `np.array(linestring)`:

```
In [36]: l = LineString([(np.random.rand(), np.random.rand()) for _ in range(3)])

In [37]: print(l)
LINESTRING (0.8560682567081583 0.439905317953636, 0.2794390645957525 0.7960846244890314, 0.9887814274354602 0.198297465764563)

In [38]:  np.array(l)
Out[38]: 
array([[ 0.85606826,  0.43990532],
       [ 0.27943906,  0.79608462],
       [ 0.98878143,  0.19829747]])
```

so it would result in an object array of var-length arrays, not necessarily efficient, but it would be nice if densification could be avoided.

> Previously it was used for the spatial index operations, but this is no longer necessary if we continue to use the GEOS spatial index rather than libspatialindex.

I assume we can easily replace all internal usage of rtree/libspatialindex, but do you think we could also replace the `sindex` attribute? (so users can use the index -> would need a python interface for the geos STRTree)

**Comment by jorisvandenbossche** [comment]
Going to merge this, so it is easier to use in other PRs. Can always add more benchmarks later.

**Pull request merged**
