### PR TITLE
CI: add fiona latest to test runs

### PR DESCRIPTION
**Pull request by snowman2**
https://github.com/Toblerity/Fiona/issues/1053

I am checking to see if the CRS changes break anything.

### CODE REVIEW

**Comment by martinfleis** [comment]
Looking good!

**Comment by snowman2** [comment]
Logs say `fiona==1.9a1` and the CRS updates are in `1.9a2`. Must not have released them to pypi yet.

**Comment by snowman2** [comment]
Do you think this would be a good addition for geopandas? If so, would you prefer installing from pip or git?

**Comment by martinfleis** [comment]
I would prefer installing from wheels so we don't have to compile here.

**Comment by snowman2** [comment]
> I would prefer installing from wheels so we don't have to compile here.

That makes sense for the CI build. One downside is that it won't work on Windows for local development. Is that okay?

**Comment by snowman2** [comment]
Actually, I just realized that conda-forge has some patches it applies for Windows, so the experience will be the same either way.

**Review by martinfleis — APPROVED** [review]
Thanks, it seems that this does the job.

**Pull request merged**
