### PR TITLE
ENH: Add error checking to CRS; framework for future improvements

### PR DESCRIPTION
**Pull request by nickeubank**
Currently, CRS validity isn't checked unless a user attempts to use `to_crs`. This way it's checked when run.

In addition, if https://github.com/jswhit/pyproj/pull/78 gets integrated, this offers scaffolding to convert all CRS strings to informative CRS strings, so if someone uses an EPSG code, the CRS will be converted to a string with actual parameters. 

@micahcochran Here's my interest in keeping `pyproj` #315 

(as evidence of value, note several updates to tests with improper syntax!)

### CODE REVIEW

**Comment by micahcochran** [comment]
Your PR checks if pyproj accepts the proj4 string CRS, and is used to test the CRS validity.

I don't know if it is such a good idea to take off the appended 'epsg:' from epsg codes.  Geopandas may want to add closer support for ESRI codes or some other authority. (Frankly, ESRI codes are already if you give it a proj4 string "+init=esri:###")

I usually want details such as projection parameters to be in the background.  I want geopandas to handle those details for me.   I could import pyproj/PyCRS or whatever to tell me more about the projection.  Perhaps projection validity should be one of those

What use are the projection's parameters for geopandas?

GDAL could also do CRS validity checking.  I'm expanding on what I expressed in #315.   GDAL's OGRSpatialReference has a functions for getting [Proj4 string](http://www.gdal.org/classOGRSpatialReference.html#af1a29550373c2c14bd11514641e58e7c) and [an EPSG code](http://www.gdal.org/classOGRSpatialReference.html#a8a5b8c9a205eedc6b88a14aa0c219969), which could validate the CRS.  Along with other many other CRS representation. There is [osgeo osr](http://gdal.org/python/osgeo.osr.SpatialReference-class.html) if you want try the Python swig bindings.  (My limited experience of with it is that it is quirky.)

OGRSpatialReference has some decent functions for getting the projection parameters, such as [GetLinearUnits](http://www.gdal.org/classOGRSpatialReference.html#af2821ab555a3bb2d6bb1df49d076a198).

**Comment by nickeubank** [comment]
Some of these comments relate to handling of proj4 strings in general, and I think are great subjects of discussion. For example, removal of the epsg prefix. My goal with this is to error check in a manner consistent with the `to_crs` function so if the CRS checks out here, it will run there. At the moment, that's written to take epsg codes without prefix. 

Regarding the value of parameters, I think there are lots of times users may want to see their parameters (I know I do). I agree I want them in the background so I don't HAVE to engage with them, but I also want to be able to check them. 

Units, in particular, are something I think is really useful to have exposed to the user -- if you want to buffer a fixed distance, you need to know the map units! Users can always go check spatialreference.org, but its easy to include, and users can add tests to ensure the units are right using the string if they want to. 

Similarly, knowing the datum can be informative for picking how to re-project data -- within-datum re-projections tend to have fewer errors than cross-datum re-projections, as I understand it. 

regarding `gdal`, you're right -- if we want to switch to another projection management system, that's fine by me, provided it can provide this functionality. My point is just that I wanted this, and I know it's in `pyproj`.

**Comment by nickeubank** [comment]
(converting projection strings based on an `init` argument into a string with the full projection specification is also what the `sp` package does in R, for what it's worth)

**Comment by micahcochran** [comment]
Thank you for the consideration and feedback.  This gives me a better idea of where you are headed.

I can understand geopandas having unit awareness.

I think at a certain point it is better to just import the best tool for the job of handling projections whether it is pyproj, PyCRS, or whatnot.

>Similarly, knowing the datum can be informative for picking how to re-project data -- within-datum re-projections tend to have fewer errors than cross-datum re-projections, as I understand it.

Those types of question depend upon how close is close enough, and rely upon how accurate projection transformation libraries are.

You can definitely make code that warns the end programmer/user that a particular transformation may make their data less accurate.  There is a point in which software

I would like a function that allows for figuring out if two projections are equal or similar.

`sp` is for R, as `pyproj` is to Python.  Both packages are PROJ.4 wrappers.

**Comment by nickeubank** [comment]
@micahcochran  

On the "best tool", I think we're in agreement -- I'm ok with any proj.4 wrapper that can offer these features. I just knew that `pyproj` has projection definition available. I'm amenable to any tool that can offer that!

We can probably save the conversation about making projection definitions available for when that becomes implementable. For now, does this error checking seem reasonable? If you'd like to submit a PR to move to a different projection management system, I'm open to it, but so long as `to_crs` is using pyproj, seems like we should error check against `pyproj`.

**Comment by micahcochran** [comment]
> For now, does this error checking seem reasonable?

`pyproj` will tolerate accept some garbage in a strings as long as there is a valid projection name, and one valid looking parameter.  (I have no idea if PROJ.4's API will accept this or not.)

```Python 
In [9]: p=Proj('+init=epsg:4326 +zed=99 ajsklfdj;,cb;0324923049-23')

In [10]: p.srs
Out[10]: '+units=m +init=epsg:4326 +zed=99 ajsklfdj;,cb;0324923049-23'

In [24]: p=Proj('+proj=latlong +black=beard blah blah blah')

In [25]: p.srs
Out[25]: '+units=m +proj=latlong +black=beard blah blah blah'
```

If you have an entirely garbage string, it will give a RuntimeError.  If your goal is to validate a PROJ.4 string, it may be better than nothing at validation.  (Fiona is stricter with parsing PROJ.4 string.)   This test isn't going to be that strict.

I don't know if validating it is a good idea or not,  I almost always work with data that has projection information.

**Comment by nickeubank** [comment]
@micahcochran 

OK -- would you rather try and just replace `pyproj` with `fiona.crs` everywhere and do error checking through `fiona.crs`?

(Unfortunately, I find setting projection information to be a common application in social science, though it's almost always the same manipulation: it seems very common to get tabular data with latitudes and longitudes for points, so converting and setting to EPSG 4326 seems to happen in almost every workflow my students and I write)

**Comment by micahcochran** [comment]
@nickeubank 

It seems like `fiona.crs` filters out invalid parameters, which is seems like a step in the right direction.  During verification, should the user be warned that there are invalid parameters in a PROJ.4 string?

You might try `PyCRS`, which is currently in beta.  I recommend installing the repository version.  `pyproj` may need to be in the mix too.  I haven't considered this problem, so I don't know the best way to solve it.

**I have no objections to this PR.**

(It would be nice if geopandas, fiona, and pyproj could work together to mostly hide and handle projection information, so you don't have to reset after doing an operation.  Along those same lines, I was thinking about changing the \__geo_interface\__ spec to allow for crs information and a couple other ways of making the crs follow the data.  None of which have gotten the ground.  Working on the municipal side, state plane coordinates are the norm and using EPSG:4326 is rare unless the data was GPS collected.)

**Comment by nickeubank** [comment]
@jorisvandenbossche sounds like we're ok with merging this?

@micahcochran OK, let's return to this in #315 -- seems like given your experience (and examples here) moving to `fiona.crs` may both reduce dependencies and improve error checking.

**Comment by jorisvandenbossche** [comment]
I am also OK with this PR, but an alternative to a property setter, would be a `set_crs` method (similar to `to_crs`) which would allow keyword arguments. 
This way, one could do eg `gdf.set_crs(epsg=4326)` instead of needing to know the string format (`gdf.crs = {'init' :'epsg:4326'}`) (https://github.com/geopandas/geopandas/issues/245)

**Comment by snowman2** [comment]
This is addressed in #1101

**Comment by martinfleis** [comment]
Closed by #1101

**Pull request closed without merging**
