### PR TITLE
DOC: Add buckaroo data table to the community docs

### PR DESCRIPTION
**Pull request by paddymul**

### CODE REVIEW

**Review by martinfleis — APPROVED** [review]
Thanks for the addition!

**Comment by paddymul** [comment]
What is Buckaroo:

[Buckaroo](https://github.com/paddymul/buckaroo) is a modern data table viewer for Jupyter notebooks, tailored for exploratory data analysis tasks, which provides useful, sensible views and hooks for everyday data analysis. 
In addition to standard table viewing features, Buckaroo comes with existing built-in analysis that is extensible by users.  This works on Pandas, Polars, and now GeoPandas! 
geopandas-buckaroo

Here is a video demonstrating Buckaroo and GeoPandas:
https://www.youtube.com/watch?v=T39DrGFq46A

**Comment by paddymul** [comment]
I normally would post the above to a mailing list.  I wanted to announce to the GeoPandas community that my tool supports this library.  I would appreciate it if you could include a link in your docs.  Let me know about any feedback you have on buckaroo or this PR

**Comment by martinfleis** [comment]
One note - I would be careful about using SVG as some geometries may be quite large and browsers may struggle to render it freezing the window.

**Comment by paddymul** [comment]
> One note - I would be careful about using SVG as some geometries may be quite large and browsers may struggle to render it freezing the window.

Thanks for the heads up.  Buckaroo has built in downsampling. The `GeopandasSVGBuckarooWidget` samples to no more than 2k rows vs 10k for all other renderers..  `GeopandasSVGBuckarooWidget` is also not enabled by default.

**Comment by m-richards** [comment]
Thanks for sharing this @paddymul, certainly looks like a useful library, will try and check it out sometime soon.

**Pull request merged**
