### PR TITLE
MAINT: use BinaryPredicate Enum for PyGEOS predicates

### PR DESCRIPTION
**Pull request by adriangb**
Compat with changes in https://github.com/pygeos/pygeos/pull/263#

ccing @brendan-ward

### CODE REVIEW

**Review by martinfleis — APPROVED** [review]
Thanks! It is also backwards compatible (with pygeos 0.8, I was a bit worried about that when I saw the change).

**Comment by adriangb** [comment]
Nice! To be honest I didn't even check backwards compatibility, I'm glad you did...

**Review by brendan-ward — APPROVED** [review]
Thanks @adriangb for getting to this so quickly!

**Comment by adriangb** [comment]
@martinfleis  this is passing I think, ready for a merge?

**Comment by martinfleis** [comment]
Dev is failing due to #1873. Will wait until that one is merged.

**Comment by martinfleis** [comment]
@adriangb Can you update from master?

**Comment by adriangb** [comment]
> @adriangb Can you update from master?

Done. All passing now

**Comment by martinfleis** [comment]
Thanks @adriangb!

**Pull request merged**
