### PR TITLE
COMPAT: suppress numpy1.21 deprecation warnings for Shapely < 1.8

### LINKED ISSUE #2013: BUG: exception was ignored while fetching the attribute __array_interface__
This issue is essentially described [here](https://gis.stackexchange.com/q/402987).

In a miniconda environment on any OS using a conda-forge channel with geopandas 0.9.0, shapely 1.7.1, pygeos 0.10.1 and numpy 1.21.0, take this example `test_numpy_dep.py` script:
```python
import geopandas
from random import random
from shapely.geometry import Polygon

geoms = [Polygon((random(), random()) for _ in range(3)) for _ in range(3)]
gdf = geopandas.GeoDataFrame(geometry=geoms)
```
and run it via `python -W all test_numpy_dep.py`. The console will be flooded one warning per geometry, each showing:
> C:\Users\mtoews\Miniconda3\envs\pyforge\lib\site-packages\geopandas\_vectorized.py:106: DeprecationWarning: An exception was ignored while fetching the attribute `__array_interface__` from an object of type 'Polygon'.  With the exception of `AttributeError` NumPy will always raise this exception in the future.  Raise this deprecation warning to see the original exception. (Warning added NumPy 1.21)

(similar on Linux, I'm just happen to be sitting at Windows desktop now).

The relevant [NumPy release note](https://github.com/numpy/numpy/releases/tag/v1.21.0) is titled "Exceptions will be raised during array-like creation". I'll admit I don't 100% follow the expected changes.

Note there is a related shapely deprecation warning, see #1659. Also, shapely 1.8 (not released yet) will [deprecate the array interface](https://github.com/Toblerity/Shapely/pull/955).

#### Output of ``geopandas.show_versions()``

<details>

```
SYSTEM INFO
-----------
python     : 3.9.6 | packaged by conda-forge | (default, Jul 11 2021, 03:37:25) [MSC v.1916 64 bit (AMD64)]
executable : C:\Users\mtoews\Miniconda3\envs\pyforge\python.exe
machine    : Windows-10-10.0.17134-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 3.3.1
GDAL data dir: None
PROJ       : 8.0.1
PROJ data dir: C:\Users\mtoews\Miniconda3\envs\pyforge\Library\share\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.9.0
pandas     : 1.2.5
fiona      : 1.8.20
numpy      : 1.21.0
shapely    : 1.7.1
rtree      : 0.9.7
pyproj     : 3.1.0
matplotlib : 3.4.2
mapclassify: 2.4.2
geopy      : None
psycopg2   : 2.9.1 (dt dec pq3 ext lo64)
geoalchemy2: None
pyarrow    : None
pygeos     : 0.10.1
```
</details>

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Closes #2013

### CODE REVIEW

**Comment by martinfleis** [comment]
There's still one instance of this warning in our tests. Seems to come from pandas https://github.com/geopandas/geopandas/pull/2072/checks?check_run_id=3388495474#step:6:3000

**Comment by jorisvandenbossche** [comment]
Yeah, I _think_ that comes from a pandas call in the tests, and not from actual geopandas code (if someone does `pd.DataFrame({'col": [list of geometries]})`, then we have of course no control over that to silence warnings). And I think that is fixed in https://github.com/geopandas/geopandas/pull/2075

**Comment by jorisvandenbossche** [comment]
Ah, I see that I fixed a similar case like that here in the tests as well. So I could have fixed included it here as well.

**Comment by martinfleis** [comment]
If that gets fixed in #2075 we can merge this one.

**Pull request merged**
