### PR TITLE
CI: install pyogrio from conda-forge instead of pip

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
I don't think there is a reason to still install it with pip (originally this was done to install the latest main version)

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
CI for WIndows and MacOS is failing -> https://github.com/conda-forge/gdal-feedstock/pull/629#issuecomment-1255564052

**Review by martinfleis — APPROVED** [review]
Conditional approval assuming the last env will also pass. Thanks!

**Comment by jorisvandenbossche** [comment]
Hmm, it's taking a very long time in the conda step ..

**Comment by martinfleis** [comment]
I did finish eventually. Thanks!

**Pull request merged**
