### PR TITLE
ENH: plot with single colors

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Add the ability to specify `color` in `plot()` to plot all points/lines/polygons in a single color.

You can see it at work in this notebook: http://nbviewer.ipython.org/gist/jorisvandenbossche/47e6d587eec39a8357f0#

### CODE REVIEW

**Comment by kjordahl** [comment]
LGTM, but we're going to have merge conflicts with #186. In what order would you like to merge these? (There's still a minor fix needed for Python 3 in #186).

**Comment by jorisvandenbossche** [comment]
You can merge #186 first (if travis passes now), then I will rebase this one afterwards. Just also have to see how it works together with #229

**Comment by jorisvandenbossche** [comment]
@kjordahl rebased this PR

**Comment by kjordahl** [comment]
:+1:

**Comment by jorisvandenbossche** [comment]
Thanks for merging!

**Pull request merged**
