### PR TITLE
Refactor: cythonize geometry series operations

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
This is a partially squashed, rebased on master, cleaned-up (removed sjoin for now) version of https://github.com/geopandas/geopandas/pull/467.

I will merge this into a geopandas-cython branch in the geopandas repo. So subsequent PRs to further work on this can target that branch.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@mrocklin will merge this so we can further work in PRs. If you rebase the old branch on this, you should get a rather clean diff of all the sjoin things (apart from some removed commented code)

**Comment by mrocklin** [comment]
Great!  Thank you so much for doing this.  I'm a little ashamed that you had to clean up my commit history :)

**Comment by jorisvandenbossche** [comment]
> I'm a little ashamed that you had to clean up my commit history :)

No, no, that is just due to my unneeded 'desire' to have a nice history and preserve some credits to different people, I could also have squased it entirely to have an easier rebase :-)

**Comment by jorisvandenbossche** [comment]
Not waiting on travis for merging as this will failing, so merging.

We can still use this PR to comment on the code also after it is merged

**Pull request merged**
