### PR TITLE
BUG: Properly handle geometry_encoding if None and add docs

### PR DESCRIPTION
**Pull request by m-mohr**
The geometry_column defaults to None, but in the following code this may lead to issues.
Add documentation for the parameter.

### CODE REVIEW

**Comment by m-richards** [comment]
@m-mohr can you share a reproducer for this? To me it looks like you must be calling `_create_metadata` directly, it seems like it's always populated correctly from within to_parquet/to_feather. While your fix works, I'm wondering if it's better that this is explicitly passed, rather than an assumed deafault within our internal code.

**Comment by m-mohr** [comment]
@m-richards Yes, due to #3182 I had to copy some code over from geopandas to my project until #3182 is solved in geopandas. 
As such I'm calling some internal functions directly, but regardless of whether it's correctly set by another function, shouldn't the internal functions in geopandas be somewhat self-contained and react properly? I mean None is the default value and the function fails in that case. That seems like a bad practice to me and could lead to potential issues in the future...

**Comment by m-richards** [comment]
@m-mohr totally agree this is something we should fix - it's just useful to understand how it popped up in the first place. I think the approach of defaulting to wkb is fine - it's at least consistent with the higher level api.

Do you mind adding a regression test to `geopandas/io/tests/test_arrow.py::test_create_metadata` to cover this geometry_encoding=None case?

**Comment by m-mohr** [comment]
@m-richards Like in https://github.com/geopandas/geopandas/pull/3412/commits/02edc92f31677f12455147ee825e0838bfb561e0 ?

**Review by m-richards — APPROVED** [review]
Thanks for that @m-mohr!

I think this one doesn't need a changelog entry since it's only really an internal facing change.

**Review by martinfleis — APPROVED** [review]

**Pull request merged**
