### PR TITLE
Refactor tests

### LINKED ISSUE #168: Tests not distributed in the pypi source
This makes it trickier to test a geopandas install -- I encountered this issue because I am trying to build a conda package for geopandas.

I believe the best practice would be to make "geopandas.tests" a Python module (this is basically want pandas does). That would ensure tests get distributed with the source, and also let you run tests with something like `nosetests geopandas`.

### PR DESCRIPTION
**Pull request by kjordahl**
This puts the tests in the main geopandas package, instead of the root level of the repository.

Includes a few minor additional test cleanups.

Fixes #168

### CODE REVIEW

**Comment by kjordahl** [comment]
Travis fails with 1 error:
```
geopandas/io/tests/test_io.py:5: in <module>
    from geopandas import read_postgis, read_file
E   ImportError: No module named geopandas
```
That doesn't make sense to me, as geopandas imports work everywhere else.

???

**Comment by kjordahl** [comment]
Got it, the new test directories didn't have a `__init__.py` file. Tests passing again.

**Comment by jorisvandenbossche** [comment]
@kjordahl Looks good to me. Ready to merge?

**Comment by kjordahl** [comment]
@jorisvandenbossche I'm :+1: to merge this, but it's going to cause some merge conflicts with outstanding PRs. It looks like #229 already needs some resolution. #241 should be easy enough to resolve either way.

**Comment by IamJeffG** [comment]
@kjordahl  As owner of #241 I have no problem with you merging this before me.  Go for it!

**Comment by jorisvandenbossche** [comment]
@kjordahl This needs a rebase in the meantime. Would be good to include this in the 0.2 release

**Comment by jorisvandenbossche** [comment]
@kjordahl Do you have time for this? Otherwise I can also do the rebase

**Comment by auvipy** [comment]
looks ok. apart from that how about moving to py.test for testing framework?

**Comment by jorisvandenbossche** [comment]
@kjordahl rebase it in #309

**Pull request closed without merging**
