### PR TITLE
CLN: decrease indent via combining `with`

### PR DESCRIPTION
**Pull request by Zeroto521**
Combine two `with` to one, and decrease indent for reading.

### CODE REVIEW

**Comment by martinfleis** [comment]
Isn't the existing way a bit more readable/understandable? (I don't really mind this change, just don't see the reason for it)

**Comment by jorisvandenbossche** [comment]
I think I also find the original a bit easier to read

**Comment by Zeroto521** [comment]
These are my thinking.

`with` is similar to `if`.

```python
# if there have some short conditions, we would combine them into one line via `and`.
if a_short_condition:
    if another_short_condition:
        ...

# should combine them, this would be fine
if a_short condition and another_short_condtion:
    ...

# compare to `with` in the same situation
with a_short_env as env1:
    with another_short_env as env2:
        ...

# also need to combine one
with a_short_env as env1, another_short_env as env2:
    ...


# for long condition, we have two choices.
# this would be good.
if just_a_really_very_long_condition:
    if just_another_really_very_long_condition:
        ...

# another is using `and` and `()`
if (
    just_a_really_very_long_condition and 
    just_another_really_very_long_condition
):
    ...

# compare to `with` in the same situation
# this would be good.
with just_a_really_very_long_env as env1:
    with just_another_really_very_long_env as env2:
        ...

```

**Comment by martinfleis** [comment]
Sure, but that doesn't change the fact that it is less readable. Though `with` can be written similarly to `if`, it is conceptually different (and not so common), which has a different implication on the readability of the code.

A shorter code does not always mean better code.

**Pull request closed without merging**
