### PR TITLE
ENH: add on_invalid parameter to from_wkt and from_wkb

### LINKED ISSUE #2962: ENH: Add on_invalid parameter to from_wkb
WKB geometries may contain invalid geometries that cannot be properly extracted, which by default raises exceptions.  This can prevent reading geometries from a file (e.g., [#2791]) which are not under control of the user and easily fixed.

We can expose the  [`on_invalid` parameter](https://shapely.readthedocs.io/en/stable/reference/shapely.from_wkb.html#shapely-from-wkb) (also available for pygeos) and then readers (e.g., pyogrio) can also support this parameter to skip or warn on reading invalid geometries.

### PR DESCRIPTION
**Pull request by theroggy**
Resolves #2962

Reference #2791

Remark: I noticed a method called `_from_wkb_or_wkb` in `GeoSeries`, I suppose this should be `_from_wkb_or_wkt`? If this is the case, shall I change this in this PR or in a seperate one?

### CODE REVIEW

**Review by martinfleis — APPROVED** [review]
Thanks! Looks fine to me!

> I suppose this should be _from_wkb_or_wkt? If this is the case, shall I change this in this PR or in a seperate one?

you can change that here.

**Comment by theroggy** [comment]
`_from_wkb_or_wkb` in GeoSeries has been renamed to `_from_wkb_or_wkt`.

**Review by jorisvandenbossche — APPROVED** [review]
Looks good, thanks!

**Comment by jorisvandenbossche** [comment]
Pushed a small commit to address my one comment, and also removed the parametrization (then the if/elif/else wasn't needed, that felt a bit simpler to me)

**Pull request merged**
