### PR TITLE
Set nominatim as default geocoding service

### PR DESCRIPTION
**Pull request by jdmcbr**
I hesitated to do this before for the docs, but it is nice to have the
default provider be one that works without an API key (which is now
required for google). The downside of this is that geocodefarm has only
been an option since May 2018, so if someone tries just running the
examples and doesn't have prior experience, they'll get a crash due
to a missing provider rather than a crash due a missing API key.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Seems like a good idea to change the default. 
I don't know much about this, but geocodefarm is a sensible default? Has geopy some concept of default provider?

**Comment by jdmcbr** [comment]
@jorisvandenbossche Good question. There isn't a default provider, but the `geopy` docs do use Nominatim (part of openstreetmap) as their example service. Nominatim doesn't have a cap on calls, but require no more than 1 request per second, and also note that "Results must be cached on your side. Clients sending repeatedly the same query may be classified as faulty and blocked" (https://operations.osmfoundation.org/policies/nominatim/). geocodefarm has a limit of 250 free calls per day, and on their side they limit to 4 requests per second (by IP), so for the infrequent geocoding I've done, I've used them. But Nominatim may make more sense as the default.

**Comment by jorisvandenbossche** [comment]
Thanks!

**Comment by jorisvandenbossche** [comment]
@jdmcbr Just noticed this in the travis log:

>  /home/travis/build/geopandas/geopandas/geopandas/tools/geocoding.py:122: DeprecationWarning: Using Nominatim with the default "geopy/1.18.1" `user_agent` is strongly discouraged, as it violates Nominatim's ToS https://operations.osmfoundation.org/policies/nominatim/ and may possibly cause 403 and 429 HTTP errors. Please specify a custom `user_agent` with `Nominatim(user_agent="my-application")` or by overriding the default `user_agent`: `geopy.geocoders.options.default_user_agent = "my-application"`. In geopy 2.0 this will become an exception.

For our testing we can provide a "geopandas-ci" user_agent, but not sure what to do about it for the default value?

**Comment by jdmcbr** [comment]
Okay, that confirms my original impression reading of the terms of service, which I then thought better of on revisiting them after you raised the question about the better default service. I think I overlooked the line

> Provide a valid HTTP Referer or User-Agent identifying the application (stock User-Agents as set by http libraries will not do).

I don't really see a way to satisfy that and have nominatim as the default. :disappointed:

**Comment by jorisvandenbossche** [comment]
Yep, we will need to look for another default. Do you know of any of the other services for which the user terms would be OK for this use case? (otherwise the option might be to not have a default, but that might be a bit annoying)

**Comment by jdmcbr** [comment]
@jorisvandenbossche I didn't see anything in the geocodefarm terms of service that indicated an issue with that being the default. I think when I'd looked before when I made the update for the docs, all other providers geopy supports required an API key or were for some other reason a bad fit for use in the docs.

**Pull request merged**
