### PR TITLE
GHA: Use github.ref instead of github.ref_head in concurrency group

### PR DESCRIPTION
**Pull request by adriangb**
Attempt to fix #2121; I'm only 85% sure this will work 😛

### CODE REVIEW

**Comment by martinfleis** [comment]
I guess we won't find out until we merge.

**Comment by martinfleis** [comment]
It is running now. Thanks!

**Comment by adriangb** [comment]
Just FYI, I think the way it plays out is:
- Commit A -> Action A kicks off
- Commit B -> Action B kicks off but gets marked as pending
- Commit C -> Action C kicks off, gets marked as pending and cancels *Action B and all of the pending actions*. That is, Action A is *not* cancelled and C still waits for A.

**Comment by adriangb** [comment]
Hmm maybe it _does_ cancel non-pending jobs (in the above comment that would mean that C cancels A), based on experiments in #2122

In any case, it achieves the goal of having the last commit run and not have to wait for _all_ of the previous ones to finish

**Pull request merged**
