### PR TITLE
ENH: check for minimum version of folium

### LINKED ISSUE #2187: ENH: check for minimum version of folium
I've found that we require some recent version of folium with `explore`. I haven't yet checked which is needed but 0.8.3 that comes pre-installed in Google Colab is too old and raises an error. We should capture that and raise an informative error, instead of existing coming from folium (something about `missing 1 required positional argument: “location”`).

In case someone stumbles upon this issue trying to resolve Google Colab, just update folium.
```
!pip install folium -U
```

### PR DESCRIPTION
**Pull request by fisaenko**
Closes #2187 

Added a check for folium version, raise an error if it's less than 0.12.0. Tested locally with different folium versions - it works as expected.

### CODE REVIEW

**Comment by fisaenko** [comment]
Need to cover new lines with tests

**Review by martinfleis — COMMENTED** [review]
Can you fold it into the ImporError above? It could say `The 'folium>=0.12', 'matplotlib' and 'mapclassify' packages`...

**Review by martinfleis — APPROVED** [review]
Thanks!

**Comment by EwoutH** [comment]
Should it also be updated in the pyproject.toml?

https://github.com/geopandas/geopandas/blob/3d0ff15aaa0c7e5165aecc4f33bdb3171f04d7b0/pyproject.toml#L40

**Comment by martinfleis** [comment]
@EwoutH strictly speaking yes, but I don't think it matters that much. Feel free to open a PR if you'd like.

**Pull request merged**
