### PR TITLE
Pass colorbar kwargs when plotting a dataframe

### PR DESCRIPTION
**Pull request by swagner648**
This would allow a user to pass a dictionary of keyword arguments to the .plot() method for a DataFrame that would be used when creating the colorbar.

### CODE REVIEW

**Comment by jdmcbr** [comment]
@swagner648 How come you closed this?

**Comment by swagner648** [comment]
It was my first time submitting a pull request on GitHub and I was worried I had done it incorrectly. I later recreated a similar request which is still active, linked here: https://github.com/geopandas/geopandas/pull/741.

**Comment by jdmcbr** [comment]
@swagner648 Ah, so you did! I was looking through the closed PRs, so didn't notice there was a replacement.

**Comment by swagner648** [comment]
@jdmcbr Duly noted!

**Pull request closed without merging**
