### PR TITLE
ENH: support GeoParquet 1.0.0 spec

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
There are no spec changes between 1.0.0-b1 and 1.0.0, so it's just updating the used number for writing.

### CODE REVIEW

**Comment by martinfleis** [comment]
Do you want to cut a patch with this soon?

**Comment by jorisvandenbossche** [comment]
Yes, just opened https://github.com/geopandas/geopandas/issues/3068

**Review by martinfleis — APPROVED** [review]
Thanks!

**Review by brendan-ward — APPROVED** [review]
Thanks @jorisvandenbossche !

**Comment by zaneselvans** [comment]
@jorisvandenbossche It looks like [the docstring for GeoDataframe.to_parquet()](https://geopandas.org/en/v0.14.1/docs/reference/api/geopandas.GeoDataFrame.to_parquet.html) might have missed being updated when this PR was merged? There's still a warning about [only tracking v0.4.0](https://github.com/geopandas/geopandas/blob/main/geopandas/geodataframe.py#L1042-L1109) and the allowed values for `schema_version` don't include 1.0.0.

**Pull request merged**
