### PR TITLE
TST: A random geometry based execution test

### PR DESCRIPTION
**Pull request by bretttully**
@jorisvandenbossche This is the kind of thing that I have found to be useful when hunting for rare edge cases that can then be boiled down to unit tests.

### CODE REVIEW

**Comment by bretttully** [comment]
Apparently `pandas 1.3.3` introduces that `union` error. Here is my current prod environment that has not had any issues for many months

<details>

```
********************************************************************************
                                     count      mean       std       min       25%       50%       75%       max
time_gdf1_gdf1_overlay_intersection  120.0  0.369678  0.064900  0.266073  0.329170  0.361242  0.404734  0.692790
time_gdf1_gdf2_overlay_intersection  120.0  0.432845  0.072546  0.307217  0.378908  0.418968  0.478421  0.645013
time_gdf2_gdf2_overlay_intersection  120.0  0.368695  0.067615  0.257175  0.322044  0.353698  0.405656  0.543002
time_gdf1_gdf1_overlay_union         120.0  0.843470  0.124707  0.579735  0.749008  0.843675  0.939320  1.113249
time_gdf1_gdf2_overlay_union         120.0  2.008463  0.236896  1.528352  1.831074  2.051567  2.181993  2.557439
time_gdf2_gdf2_overlay_union         120.0  0.950119  0.129016  0.710583  0.878272  0.932794  0.984228  1.383771
time_gdf1_gdf1_overlay_difference    120.0  0.266752  0.042037  0.176952  0.240852  0.263385  0.289129  0.432569
time_gdf1_gdf2_overlay_difference    120.0  0.420328  0.072124  0.253108  0.371770  0.418721  0.456118  0.706673
time_gdf2_gdf2_overlay_difference    120.0  0.262686  0.051341  0.146180  0.234729  0.258632  0.286939  0.517161
********************************************************************************
{'err_gdf1_gdf1_overlay_difference': array([], dtype=object),
 'err_gdf1_gdf1_overlay_intersection': array([], dtype=object),
 'err_gdf1_gdf1_overlay_union': array([], dtype=object),
 'err_gdf1_gdf2_overlay_difference': array([], dtype=object),
 'err_gdf1_gdf2_overlay_intersection': array([], dtype=object),
 'err_gdf1_gdf2_overlay_union': array([], dtype=object),
 'err_gdf2_gdf2_overlay_difference': array([], dtype=object),
 'err_gdf2_gdf2_overlay_intersection': array([], dtype=object),
 'err_gdf2_gdf2_overlay_union': array([], dtype=object)}
```

</details>

Version info:

<details>

SYSTEM INFO
-----------
python     : 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 16:22:27)  [GCC 9.3.0]
executable : /opt/conda/bin/python
machine    : Linux-5.10.47-linuxkit-x86_64-with-glibc2.10

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.9.1
GEOS lib   : /opt/conda/lib/libgeos_c.so
GDAL       : 3.2.1
GDAL data dir: /opt/conda/share/gdal
PROJ       : 7.2.0
PROJ data dir: /opt/conda/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.9.0
pandas     : 1.1.5
fiona      : 1.8.18
numpy      : 1.20.3
shapely    : 1.7.1
rtree      : 0.9.7
pyproj     : 3.0.1
matplotlib : 3.4.1
mapclassify: None
geopy      : 2.1.0
psycopg2   : 2.8.6 (dt dec pq3 ext lo64)
geoalchemy2: None
pyarrow    : 3.0.0
pygeos     : None

</details>

**Comment by bretttully** [comment]
Closing for now, but can reopen if this is something that is useful in the future.

**Comment by martinfleis** [comment]
@bretttully sorry for the slow response. I think we want to include this, we are just extremely behind our review process and prioritise bugs at the moment more than additional tests. I'll get to this at some point if it stays open.

**Comment by bretttully** [comment]
> @bretttully sorry for the slow response. I think we want to include this, we are just extremely behind our review process and prioritise bugs at the moment more than additional tests. I'll get to this at some point if it stays open.

Of course! Sorry, I hope my closing didn't come across as passive aggressive! I was just cleaning up my GitHub.

**Comment by bretttully** [comment]
Extended this a bit while testing out shapely v2: https://github.com/bretttully/shapely-v2

**Comment by bretttully** [comment]
Renamed the base branch from this PR -- didn't realise it would close it so have re-opened here: https://github.com/geopandas/geopandas/pull/2755

**Pull request closed without merging**
