### PR TITLE
RLS 0.6.2 backports

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
@martinfleis starting some backports for a 0.6.2 release

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@martinfleis other things you think of to include? 
Otherwise I can do a quick release today

**Comment by martinfleis** [comment]
I don't think so. Go for it, that RGB(A) issue is apparently causing a lot of troubles.

**Comment by jorisvandenbossche** [comment]
OK, that's a good reason to release now ;)

**Comment by jorisvandenbossche** [comment]
Done! 
https://github.com/geopandas/geopandas/releases/tag/v0.6.2 and https://pypi.org/project/geopandas/0.6.2/, conda-forge will automatically happen in a bit

**Pull request merged**
