### PR TITLE
[cython refactor] update geopandas-cython branch with master

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
(WIP: will further add the commits of master to this PR)

After those cherry picks, I ran the tests but currently they segfault on this test (did not yet investigate why):

geopandas/tests/test_geoseries.py::TestSeries::test_coord_slice_with_zero Segmentation fault (core dumped)

### CODE REVIEW

**Comment by mrocklin** [comment]
This works for me.  

   ===== 19 failed, 324 passed, 6 skipped, 9 xfailed in 91.44 seconds =====

Although I didn't recreate the same environment used in travis-ci, so maybe that is related.

**Comment by jorisvandenbossche** [comment]
I get this strange behaviour:

```
In [2]: from geopandas import GeoSeries

In [3]: from shapely.geometry import Point

In [4]: gs = GeoSeries([Point(x, x) for x in range(-3, 4)])

In [5]: gs.cx[:0, :0]
/home/joris/scipy/geopandas/geopandas/_block.py:70: FutureWarning: in the future, boolean array-likes will be handled as a boolean array index
  values = self.values[key]
Out[5]: I am densified (7 elements)

0    POINT (-2 -2)
1    POINT (-2 -2)
2    POINT (-2 -2)
3    POINT (-2 -2)
     POINT (-3 -3)
     POINT (-3 -3)
     POINT (-3 -3)
dtype: object

In [6]: res = _

In [8]: res._data
Out[8]: 
SingleBlockManager
Items: Int64Index([0, 1, 2, 3], dtype='int64')
GeometryBlock: 7 dtype: object

In [9]: len(res)
Out[9]: 4

In [10]: res.index
Out[10]: Int64Index([0, 1, 2, 3], dtype='int64')

In [11]: res.values
I am densified (external_values, 7 elements)
Out[11]: 
array([<shapely.geometry.point.Point object at 0x7f7b6da99630>,
       <shapely.geometry.point.Point object at 0x7f7b6da99ef0>,
       <shapely.geometry.point.Point object at 0x7f7b6daa9c88>,
       <shapely.geometry.point.Point object at 0x7f7b6daa9cc0>,
       <shapely.geometry.point.Point object at 0x7f7b6daa9eb8>,
       <shapely.geometry.point.Point object at 0x7f7b6daa9d68>,
       <shapely.geometry.point.Point object at 0x7f7b6daa9e80>], dtype=object)

In [12]: res._values
Out[12]: <geopandas.vectorized.GeometryArray at 0x7f7b6df12320>

In [13]: len(res._values)
Out[13]: 7
```

So the resulting series has an invalid underlying structure (more data than its length).

The above runs, but if then passed to `geom_equals` it segfaults.

**Comment by mrocklin** [comment]
I've pushed a commit that replaces a lost import.

Classifying some of the other errors that are probably my job to fix:

1.  SIndex probably needs to be rewritten to use GEOS's STRTree
2.  I need to rename GeometryArray.parent to base and align with numpy's use

I'm not sure what to do with the `GeometryArray._reduce` errors.  I suspect that these are a Pandas issue.

**Comment by jorisvandenbossche** [comment]
My problem seems to be with boolean indexing with a Series (with array it works fine):

```
In [1]: from shapely.geometry import Point

In [2]: from geopandas import GeoSeries

In [3]: gs = GeoSeries([Point(x, x) for x in range(-3, 4)])

In [5]: mask = np.array([True, False, True, False, True, False, True])

In [6]: gs[mask]
Out[6]: I am densified (4 elements)

0    POINT (-3 -3)
2    POINT (-1 -1)
4      POINT (1 1)
6      POINT (3 3)
dtype: object

In [7]: gs[pd.Series(mask)]
/home/joris/scipy/geopandas/geopandas/_block.py:70: FutureWarning: in the future, boolean array-likes will be handled as a boolean array index
  values = self.values[key]
Out[7]: I am densified (7 elements)

0    POINT (-2 -2)
2    POINT (-3 -3)
4    POINT (-2 -2)
6    POINT (-3 -3)
     POINT (-2 -2)
     POINT (-3 -3)
     POINT (-2 -2)
dtype: object
```

@mrocklin you cannot reproduce this ?

**Comment by mrocklin** [comment]
I'm not sure yet, here is what I get, all of which seems reasonable.  I suspect that we are getting different results due to versions of other libraries (maybe Pandas?)

```python
In [1]: import geopandas as gpd

In [2]: from shapely.geometry import Point

In [3]: gs = gpd.GeoSeries([Point(x, x) for x in range(-3, 4)])

In [4]: gs.cx[:0, :0]
Out[4]: I am densified (4 elements)

0    POINT (-3 -3)
1    POINT (-2 -2)
2    POINT (-1 -1)
3      POINT (0 0)
dtype: object

In [5]: res = _

In [6]: res._data
Out[6]: 
SingleBlockManager
Items: Int64Index([0, 1, 2, 3], dtype='int64')
GeometryBlock: 4 dtype: object

In [7]: res.index
Out[7]: Int64Index([0, 1, 2, 3], dtype='int64')

In [8]: res.values
I am densified (external_values, 4 elements)
Out[8]: 
array([<shapely.geometry.point.Point object at 0x7fd433c08b70>,
       <shapely.geometry.point.Point object at 0x7fd433c08400>,
       <shapely.geometry.point.Point object at 0x7fd433bb3080>,
       <shapely.geometry.point.Point object at 0x7fd433bb32b0>], dtype=object)

In [9]: res._values
Out[9]: <geopandas.vectorized.GeometryArray at 0x7fd433bedf98>

In [10]: res._values.data
Out[10]: array([33704256, 33704320, 33704384, 32661120], dtype=uint64)
```

I'm currently working off of this pandas commit

```
commit b41b713eece90dd8a0de36884d02ddb632ec8b3c
Author: Joris Van den Bossche <jorisvandenbossche@gmail.com>
Date:   Thu Aug 3 23:50:55 2017 +0200

    pep8
```

**Comment by mrocklin** [comment]
We might consider replacing the old travis-ci testing matrix with a newer standard environment that we can both use as a reference.

**Comment by jorisvandenbossche** [comment]
I am working with latest pandas master, and numpy 1.11.3 
The travis matrix can certainly be updated (we shouldn't try to support those old pandas versions on this branch), but it should already test against pandas master, so can see there if it segfaults there as well.

**Comment by mrocklin** [comment]
I remember needing to test against one of your branches in the past for things to work properly.  Has this branch been merged?

**Comment by mrocklin** [comment]
I've pushed a couple more commits to this branch that brings the total test failures down to 13

    === 13 failed, 330 passed, 6 skipped, 9 xfailed in 80.37 seconds ===

Sorry for using your branch like this.  I'm also happy to submit a separate PR.

**Comment by jorisvandenbossche** [comment]
> I remember needing to test against one of your branches in the past for things to work properly. Has this branch been merged?

yes, that was for the (non-truncated) repr, and has been merged

**Comment by mrocklin** [comment]
Excellent.  Switching my local environment to master ...

**Comment by mrocklin** [comment]
Still no segfaults

**Comment by mrocklin** [comment]
Given the dependence on newer pandas I'm inclined to shoot for "latest versions only" at least for the first release of a cythonized geopandas.  If people show up who need older version support then we would focus on their needs after a release.

**Comment by mrocklin** [comment]
@jorisvandenbossche how would you like to handle git history here?  Merge all of the cherry-picked commits in?  Squash?

**Comment by jorisvandenbossche** [comment]
I was planning to "Rebase and merge" those, as I want to keep the separate commits, as this branch will eventually become master.

**Comment by mrocklin** [comment]
OK.  Sounds good.  Everything here looks good to me.

**Comment by jorisvandenbossche** [comment]
Further updated with all commits from master. 
Going to merge this to not hold up further updates the geopandas-cython branch.

(and updated numpy in my dev environment, and now also down to 13 failed)

**Pull request merged**
