### PR TITLE
Added type hints for majority of geopandas functions

### LINKED ISSUE #1974: ENH: use type hints
We are currently not using [type hints](https://www.python.org/dev/peps/pep-0484/) in the code and we never discussed including them. Since all the Python versions we support work with type hints, I'd suggest implementing them across our code as well.

What we have now:

```py
def greeting(name):
    return 'Hello ' + name
```

What we should have:

```py
def greeting(name: str) -> str:
    return 'Hello ' + name
```

It would mean refactoring the existing signatures and having this model as a default for new PRs (which sometimes already happens but we request leaving it for the sake of consistency).

It is a relatively easy change, so it can be even labelled `easy first issue` for someone willing to help.

Any other thoughts on this?

### PR DESCRIPTION
**Pull request by steveberdy**
## Summary

Adds type hints and annotations for the vast majority of `geopandas` functions. All functions were changed for which type hints and annotations were useful. Pre-commit tests passed.

Fixes #1974

@martinfleis

### CODE REVIEW

**Comment by steveberdy** [comment]
@martinfleis I've been getting an error in `__init__.py` that `GeometryArray` has not been defined, despite appearing to be defined in `geopandas.array`. Any advice?

**Comment by martinfleis** [comment]
I think that it comes from `array.py` where you use `GeometryArray` in type hints before it is defined below.

**Comment by steveberdy** [comment]
@martinfleis I'm still getting the error on the first line of `__init__.py`:
```python
from geopandas._config import options  # noqa
```
I don't quite understand why `NameError` would get thrown there. One of my thoughts is that `GeometryDtype(ExtensionDtype)` references `GeometryArray` before it is defined
```python
@classmethod
def construct_array_type(cls):
    return GeometryArray
```
I can't move the class to get defined after `GeometryArray`, though, since `GeometryArray` references it as well:
```python
class GeometryArray(ExtensionArray):
    """
    Class wrapping a numpy array of Shapely objects and
    holding the array-based implementations.
    """

    _dtype = GeometryDtype()
```

Is there some work-around for this that I'm not using?

**Comment by steveberdy** [comment]
There were a lot of circular imports due to type hinting across classes. This will remove some type hints.

**Comment by martinfleis** [comment]
@steveberdy did you mean to close the PR?

**Comment by steveberdy** [comment]
I had to re-create my fork because of a push mistake. I'm not sure how to link my newest commit to this PR, so I'm going to make another one just like this. GitHub already shows 4 commits, but I don't need to push any more than one

**Comment by steveberdy** [comment]
https://github.com/geopandas/geopandas/pull/1991

**Pull request closed without merging**
