### PR TITLE
BUG: reflect changes in bool(geom) in shapely 1.7

### PR DESCRIPTION
**Pull request by martinfleis**
Shapely have changed the behaviour of boolean representation of empty geometries (https://github.com/Toblerity/Shapely/pull/812) which broke our `_binary_geo`. I have made the condition used there more explicit to avoid the issue.

### CODE REVIEW

**Comment by martinfleis** [comment]
Alright. In the meantime, there was another change on pandas master causing new fails. As there are like four pages of commits to pandas master in last 6 days (since this passed), I am struggling a bit to find what caused the issue.

**Comment by martinfleis** [comment]
Got it. https://github.com/pandas-dev/pandas/pull/30308 Pandas added new tests for ExtensionArray for which our GeometryArray was not ready :). This will require some changes in GeometryArray. I'll open separate issue for that.

**Comment by jorisvandenbossche** [comment]
Can you merge master now I merged the other PR? That should then give green tests again.

**Comment by martinfleis** [comment]
Green again. If you don't have any further comments we can merge and I'll update those red PRs to make them finally green.

**Pull request merged**
