### PR TITLE
CLN: avoid `shapely.geos` in _compat.py

### PR DESCRIPTION
**Pull request by mathause**
Potentially forgotten import and usage of `shapely.geos`. As far as I can see `shapely.geos_version` already exists in shapely v2.0.0.

### CODE REVIEW

**Comment by mathause** [comment]
I don't see how the test failure could be related and cannot reproduce locally...

**Review by jorisvandenbossche — APPROVED** [review]
Indeed, now that we require shapely > 2, this can be used from the top-level package. 
Thanks!

**Comment by jorisvandenbossche** [comment]
> I don't see how the test failure could be related and cannot reproduce locally...

Yeah, that seems strange. Let's see if that happens for other PRs as well

**Comment by theroggy** [comment]
> > I don't see how the test failure could be related and cannot reproduce locally...
> 
> Yeah, that seems strange. Let's see if that happens for other PRs as well

Yep, same in a PR of mine...

**Comment by jorisvandenbossche** [comment]
The only change in environment I can see is an update of pytest-cov to 6.0

**Comment by theroggy** [comment]
> The only change in environment I can see is an update of pytest-cov to 6.0

In my diff fontconfig also changed from 2.14.2 to 2.15.0 , but I doubt that will be the culprit.

**Comment by m-richards** [comment]
Looks to be the pytest cov change from testing

**Comment by jorisvandenbossche** [comment]
@mathause if you merge in the latest `main` branch, the error should be resolved

**Comment by mathause** [comment]
Thanks. Looks like now we have to wait for #3456 and potentially a micromamba fix.

**Comment by jorisvandenbossche** [comment]
Yeah, but with the other builds passing, that should be good enough (and indeed the mamba failures are exactly the same as on the other PR)

**Review by jorisvandenbossche — APPROVED** [review]
Thanks again!

**Pull request merged**
