### PR TITLE
BUG: Escape special characters in explore (#2657)

### LINKED ISSUE #2657: Escape special characters to avoid TemplateSyntaxError in explore
The following code has the error `TemplateSyntaxError: expected token ':', got 'a'BUG:`,

```python
import pandas as pd
import geopandas as gpd
data = [{"tweet":"I didnÃ¢â‚¬â„¢t want to do it. but I did it anyway. I looked at the Town Halls. {{{what a mess}}} they are so different. #Biden is a gentle caterpillar while #Trump is a rabid fox Ã°Å¸Â¥Âº #TownHalls #trustYourInstinct  #election2020 #holdontight #bumpyride",
"lat":40.7127281,"lon":-74.0060152}]
df = pd.DataFrame(data)
gdf = gpd.GeoDataFrame(df,geometry=gpd.points_from_xy(df.lon,df.lat),crs="epsg:4326")
gdf.explore()
```

I guess because of the {} brakets in `gdf`:

> I didnâ€™t want to do it. but I did it anyway. I looked at the Town Halls. {{{what a mess}}} they are so different. #Biden is a gentle caterpillar while #Trump is a rabid fox ðŸ¥º #TownHalls #trustYourInstinct #election2020 #holdontight #bumpyride

The bug can be reduplicated[ at colab](https://colab.research.google.com/drive/1fVtTDl1SkE1DzmPd_VvQqRe56vwmGz5Q?usp=sharing)

### PR DESCRIPTION
**Pull request by wybert**
Hi, I added the process to escape the curly braces {{}} for jinja2 templates.

Closes #2657

### CODE REVIEW

**Comment by wybert** [comment]
Hi, I just find out one check is failed,
```bash
FAILED geopandas/tests/test_dissolve.py::test_mean_dissolve - TypeError: Could not convert Staten IslandQueensBrooklyn to numeric
FAILED geopandas/tests/test_dissolve.py::test_dissolve_none_mean - TypeError: Could not convert Staten IslandQueensBrooklynManhattanBronx to numeric
FAILED geopandas/tests/test_extension_array.py::TestGroupby::test_in_numeric_groupby - AssertionError: Regex pattern did not match.
 Regex: 'does not support'
 Input: 'cannot perform sum with type geometry'
FAILED geopandas/tests/test_op_output_types.py::test_constructor_sliced_in_pandas_methods - TypeError: '<' not supported between instances of 'Point' and 'Point'
FAILED geopandas/tests/test_pandas_methods.py::test_numerical_operations - TypeError: cannot perform sum with type geometry
FAILED geopandas/tests/test_pandas_methods.py::test_groupby - TypeError: cannot perform sum with type geometry
= 6 failed, 1793 passed, 264 skipped, 11 xfailed, 2 xpassed, 2294 warnings in 97.43s (0:01:37) =
Error: Process completed with exit code 1.
```
Dose anyone know how it come?

**Comment by martinfleis** [comment]
The errors are not related to this PR (the same are on main) and can be ignored here.

**Comment by martinfleis** [comment]
Hey, thanks for the fix. Could you also add a test for this to `test_explore.py`?

**Comment by wybert** [comment]
> Hey, thanks for the fix. Could you also add a test for this to `test_explore.py`?

I just added [a test](https://github.com/wybert/geopandas/blob/3b5fb3f1486153b5d9021283d89c60d0da50e690/geopandas/tests/test_explore.py#L468) for it.

**Comment by martinfleis** [comment]
Thanks! looks good. 2 more things 
- can you remove `oryx-build-commands.txt` that is added in this PR? 
- can you add a changelog note to the Changelog.md?

**Comment by wybert** [comment]
> 

I just delete that file and add a changelog note to the Changelog.md

**Comment by jorisvandenbossche** [comment]
(FYI the failures you will see on the dev branch are unrelated: https://github.com/scipy/scipy/issues/17811)

**Review by martinfleis — APPROVED** [review]
Thanks!

**Pull request merged**
