### PR TITLE
Refactor internals based on ExtensionArray interface

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Implementing the ExtensionArray interface (for current master, not the geopandas-cython branch, as I want that we actually support the EA interface already now)

Work in progress: 
For now only targeting pandas master / 0.23.0, need to add compatibility layer for older pandas versions later. 
Started with implementing a GeometryArray, and dispatching to that for the spatial methods (this will also work for older pandas versions), now integrating in the rest of the code base.

TODO:

- [x] add compatibility layer with pandas 0.23

### CODE REVIEW

**Comment by TomAugspurger** [comment]
@jorisvandenbossche mind if I use this PR to ask for a quick status update? Any blockers here?

Is the plan to move most of the functionality to GeometryArray, and possible add a DataFrame accessor, to allow much of geopandas' functionality be available in a regular DataFrame?

**Comment by jorisvandenbossche** [comment]
No blockers at the moment (except my time), I am planning to finish it this week.

I have been rebasing the cython branch on top of this. Because that will be needed anyway, and also to see if there were things missing here in the Array class that were discovered in the cython work. 
So I will be updating this branch now with those insights, and after this is merged, open a PR with the full rebased work in cython.

> Is the plan to move most of the functionality to GeometryArray, and possible add a DataFrame accessor, to allow much of geopandas' functionality be available in a regular DataFrame?

For that, there is a discussion about that in https://github.com/geopandas/geopandas/issues/680. 
Most functionality will live on the ExtensionArray, that's already done in this PR (there are a few things that only make sense on a series/dataframe level). 
Short term, I don't have any plans myself to also add an accessor, but it should be rather easy to do after this PR.

**Comment by jorisvandenbossche** [comment]
Included `__setitem__` tests from #596 and #608 (previous fixes on the cython branch), the actual code fixes itself are no longer necessary with EAs.

**Comment by jorisvandenbossche** [comment]
There is a failure on Python 2 related to unique. I am using the WKB values:

```
In [10]: from shapely.geometry import Point

In [11]: s = GeoSeries([Point(0, 0), Point(0, 0), Point(2, 2)])

In [12]: wkb_values = np.array([p.wkb for p in s], dtype=object)

In [13]: wkb_values
Out[13]: 
array(['\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',
       '\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',
       '\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00@'],
      dtype=object)

In [14]: pd.unique(wkb_values)
Out[14]: 
array(['\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'],
      dtype=object)

In [15]: np.unique(wkb_values)
Out[15]: 
array(['\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',
       '\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00@'],
      dtype=object)
```

so pandas' `unique` method is not working correctly (np.unique does it correctly). 

On python 3.7 this works fine:

```
In [48]: pd.unique(wkb_values) 
Out[48]: 
array([b'\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',
       b'\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00@'],
      dtype=object)
```

Upcoming pandas release is already python 3 only, so no possibility to fix this upstream. Also, since we are going to drop python 2 shortly as well, simply going to skip this test.

**Comment by jorisvandenbossche** [comment]
OK, going to merge this. It's good enough for an initial pass. There are some follow-up items in https://github.com/geopandas/geopandas/issues/1000

(the travis failure is only the pandas-dev build with one failure due to a regression on pandas master)

@martinfleis @jdmcbr @ljwolf review comments / questions are certainly still welcome, want to make sure everything is clear so the internals are still approachable for people less familiar with ExtensionArrays (but most code changes are mainly limited to the extra methods on the GeometryArray for the EA interface)

**Pull request merged**
