### PR TITLE
DOC/API: clarify set_geometry handling of (name of) passed values

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
This PR started originally to fix a case of the GeoDataFrame constructor to preserve the name of a GeoSeries. So when doing `GeoDataFrame(..data.., geometry=GeoSeries(geoms, name='my_geom'))`, to result in a GeoDataFrame with a 'my_geom' geometry column (on master this currently gives 'geometry' ignoring the name of the GeoSeries).

But to fix this, I started looking at the `set_geometry` method (which is being used by the GeoDataFrame constructor). And also noticed that the method is not fully well defined / documented.

- When specifying the name of an existing column, the original geometry column is kept but the "active geometry" column is swapped to the specified column
  - However, with `drop=True`, the old geometry column is replaced with the new (so dropping one column). But, now, we don't use the specified name as the geometry column name, but fall back to the default 'geometry' -> should we preserve the specified name here?

- When specifying actual geometry values, the original geometry column gets replaced with the new values
  - Currently, we don't preserve the name of the passed values (if they have a name, i.e. a (Geo)Series). This is what this PR started with fixing.
  - But if the values have a name, it can also be an option to keep the original geometry column intact (not necessarily the default, but people could do `drop=False` to keep the original one)

See also https://nbviewer.jupyter.org/gist/jorisvandenbossche/61ba4b240a2060ec7dafdead84e13371 for a notebook exploring those options of `set_geometry`.

Thoughts?

### CODE REVIEW

**Comment by martinfleis** [comment]
> However, with drop=True, the old geometry column is replaced with the new (so dropping one column). But, now, we don't use the specified name as the geometry column name, but fall back to the default 'geometry' -> should we preserve the specified name here?

I think so. If drop=False uses specified name, it sounds more reasonable to keep in for drop=True as well. `drop` itself does not feel like it should do 'drop and rename'. And if you specifically set a column as geometry you should not be confused why it is not called 'geometry'.

> But if the values have a name, it can also be an option to keep the original geometry column intact (not necessarily the default, but people could do drop=False to keep the original one)

This is reasonable as well, as an option. I can imagine situations when it would be useful. You just have to check that the name of geoseries is not the same as existing geometry column while having drop=False.

**Comment by jorisvandenbossche** [comment]
> I think so. If drop=False uses specified name, it sounds more reasonable to keep in for drop=True as well.

Yes, I think I agree. 
The question then is: do we simply change this, or is there a way we can do this with a deprecation period. So people are for this case already passing `drop=False`, so we can't use this existing keyword any more to silence the warning + get the future behaviour. 
We *could* add a `geometry_name` argument to override the name we infer, so people could then still specify their desired name. But that seems a bit ugly in general.

Thinking about this (but independent issue), maybe we should have a `rename_geometry()` method, because currently renaming the geometry column needs something like `.rename(columns={'my_geom': 'geometry'}).set_geometry('geometry')`

**Comment by martinfleis** [comment]
> do we simply change this, or is there a way we can do this with a deprecation period

Do we see it as a bug? Or change of behaviour? If it is the bug, I would change it as a bug fix. If it is the change of intended behaviour, we should include a deprecation period.

I am not a fan of `geometry_name` model...

> maybe we should have a `rename_geometry()` method

Agree.

**Comment by martinfleis** [comment]
@jorisvandenbossche can we revive this? We have `rename_geometry` now so we don't have to deal with the `geometry_name` argument to make it easier.

> do we simply change this, or is there a way we can do this with a deprecation period

I believe that this is a bug and as such should be fixed. But it may break things, so if there's a simple way of spitting out deprecation warning in affected situations, let's do that.

**Pull request closed without merging**
