### PR TITLE
CI: speedup tests by using mamba-org micromamba action

### PR DESCRIPTION
**Pull request by theroggy**
Especially on Windows and Mac, but also on Linux, creating and cleaning up the conda env takes a big part of the testing time using setup-miniconda@v2 (with mamba). 

It seems that the action doing the same thing developed by mamba-org is a lot faster...

### CODE REVIEW

**Comment by theroggy** [comment]
The defaults channel doesn't seem to be supported, or at least the combination of defaults and conda-forge isn't ([link](https://mamba.readthedocs.io/en/latest/user_guide/troubleshooting.html#mixing-the-defaults-and-conda-forge-channels)), which seems to be necessary for some yml files...

**Comment by jorisvandenbossche** [comment]
> which seems to be necessary for some yml files...

We could also try to remove that (I suppose this stems from a _long_ time ago, it might not be necessary right now). 

Looking at the different files, I think is is only 38-minimal.yaml that has the mixture. You could try to remove the defaults channel in that file to see what that gives / what might be missing from conda-forge.

**Comment by martinfleis** [comment]
Yeah, we probably don't need to have the mixture anymore but we still shall test against defaults, not only conda-forge.

**Comment by theroggy** [comment]
For 3.8_minimal.yml, when the defaults channel is removed (so only conda-forge channel is retained), that env works properly.

However, for the 2 "defaults" yml files, about 25% of packages installed is coming from conda-forge even though the conda-forge channel is not mentioned in de yml file? So I suppose conda-forge is somewhere in the default settings for the miniconda based action?

So, because in practice the "defaults" yml's do need both channels, they fail when using micromamba...

**Comment by jorisvandenbossche** [comment]
Looking at the `38-latest-defaults.yaml` environment locally and trying to create this with micromamba, it seems that the requirement of `pyproj>=3` is what causes the conflict (and causes mamba to get some packages from conda-forge in the current CI). 
Essentially, defaults cannot currently install geopandas with a requirement of pyproj>=3 (just doing `micromamba create -n test geopandas --channel defaults` gives you pyproj 2.6, and so a simple `micromamba create -n test geopandas "pyproj>=3" --chanel defaults` gives conflicts with gdal)

For that file, if we want to keep this defaults install, the only possible short term solution I see is to install pyproj with pip. So with the following patch (updating python while we are at it) it works for me locally:

```diff
diff --git a/ci/envs/38-latest-defaults.yaml b/ci/envs/38-latest-defaults.yaml
index d995d22a..d6beb4d8 100644
--- a/ci/envs/38-latest-defaults.yaml
+++ b/ci/envs/38-latest-defaults.yaml
@@ -2,14 +2,13 @@ name: test
 channels:
   - defaults
 dependencies:
-  - python=3.8
+  - python=3.10
   # required
   - numpy
   - pandas
   - shapely
   - fiona
-  - pyproj>=3
-  - geos
+  # - pyproj>=3
   - packaging
   # testing
   - pytest
@@ -24,6 +23,7 @@ dependencies:
   - libspatialite
   - pip
   - pip:
+      - pyproj>=3
       - geopy
       - mapclassify
       - pyarrow

```

**Comment by jorisvandenbossche** [comment]
Hmm, and now that illustrates why you shouldn't mix conda and pip packages .. ;) Because this is giving test failures related to fiona and PROJ

**Comment by theroggy** [comment]
> Hmm, and now that illustrates why you shouldn't mix conda and pip packages .. ;) Because this is giving test failures related to fiona and PROJ

Yes, any type of mixing is prone to giving errors: I used to have to mix defaults and conda-forge channels for a project and that also often gave issues....

**Comment by jorisvandenbossche** [comment]
OK, looked a bit at the state of the packages in the defaults channel, and so everything there is still built with proj 6.2.1, while pyproj 3.0.0 requires a minimum of proj 7 (opened https://github.com/AnacondaRecipes/gdal-feedstock/issues/18). 

So basically you currently can't get both a recent pyproj and a gdal/fiona install using the defaults channel. So either we give up on defaults, or either we wait a bit longer with requiring pyproj 3 (looking at https://github.com/geopandas/geopandas/pull/2655, I think it would mostly be some versions checks in the tests that would need to be added back)

**Comment by martinfleis** [comment]
If the defaults is not able to keep up with the release cycle of packages they aim to ship I don't think it is our role to ensure that it all works. PROJ 6.2.1 is more than 3 years old. If we're not able to solve environment with dependencies following [NEP29](https://numpy.org/neps/nep-0029-deprecation_policy.html) or upcoming [SPEC0](https://scientific-python.org/specs/spec-0000/) then I would simply remove tests against defaults until they fix the issue on their side. This is the packaging issue a packaging provider needs to resolve.

**Comment by theroggy** [comment]
Because there is no reaction on https://github.com/AnacondaRecipes/gdal-feedstock/issues/18 and there wasn't any remark on https://github.com/geopandas/geopandas/pull/2836#issuecomment-1474858336, I removed the environments to test the defaults channel from test.yaml.

I didn't remove the env files yet from https://github.com/geopandas/geopandas/tree/main/ci/envs ... not sure if the maintainers which to keep them there to reactivate them once the problem is solved in defaults or not.

**Comment by martinfleis** [comment]
> I didn't remove the env files yet from https://github.com/geopandas/geopandas/tree/main/ci/envs ... not sure if the maintainers which to keep them there to reactivate them once the problem is solved in defaults or not.

We can actually maybe even keep them in the yaml and only comment out those two lines. That way we will more likely come back to it later, hopefully once the defaults channel resolves better.

**Review by martinfleis — APPROVED** [review]
Thanks!

**Review by jorisvandenbossche — APPROVED** [review]

**Comment by jorisvandenbossche** [comment]
Thanks!

**Pull request merged**
