### PR TITLE
Fix miscellaneous tests in test_pandas_methods

### PR DESCRIPTION
**Pull request by mrocklin**
Something that came up is how to handle this case:

```python
GeoSeries([1, 2, 3])
```

Should we use `__new__` to create a Series?  Should it be legal to have non-geometries in a GeoSeries?

cc @jorisvandenbossche

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
> Should it be legal to have non-geometries in a GeoSeries?

I think we should disallow that? (either a geometry, or nan/None) This is also the current behaviour? 
Or is there a reason to allow it?

Ah, but I see that currently (master branch), this actually returns something ..

> Should we use __new__ to create a Series? 

you mean to create a pandas.Series when the data is not geometry like?

**Comment by mrocklin** [comment]
Yes, this comes up in a few tests like test_where in `test_pandas_methods`

```python
___________________________________________________ test_where ____________________________________________________

>   geos_geom = <np.uintp_t> g.__geom__
E   AttributeError: 'numpy.bool_' object has no attribute '__geom__'

geopandas/vectorized.pyx:128: AttributeError

During handling of the above exception, another exception occurred:

s = 0    POINT (0 0)
1    POINT (1 1)
2    POINT (2 2)
dtype: object

    def test_where(s):
>       res = s.where(np.array([True, False, True]))

geopandas/tests/test_pandas_methods.py:148: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../pandas/pandas/core/generic.py:5736: in where
    raise_on_error)
../pandas/pandas/core/generic.py:5521: in _where
    cond = self._constructor(cond, **self._construct_axes_dict())
geopandas/geoseries.py:95: in __init__
    arg = from_shapely(s.values)
geopandas/vectorized.pyx:110: in geopandas.vectorized.from_shapely (geopandas/vectorized.c:3682)
    cpdef from_shapely(object L):
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   raise TypeError(msg)
E   TypeError: Inputs to from_shapely must be shapely eometries. Got True
```

**Comment by jorisvandenbossche** [comment]
@mrocklin sorry, I forgot this PR, and have now done partly similar fixes in https://github.com/geopandas/geopandas/pull/547. But fixed the merge conflicts here.

For the GeoSeries accepting non-geometries, would you like to fix that here? As that is also needed to fix the `astype(str)` (the changes in this PR are not enough for that).

**Comment by jorisvandenbossche** [comment]
Since we are now going forward with PyGEOS (to be integrated in Shapely) instead of the cython branch, this can be closed.

**Pull request closed without merging**
