### PR TITLE
Update geopandas-cython branch with changes in master

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
New round of cherry-picks of commits to master since last round.

### CODE REVIEW

**Comment by mrocklin** [comment]
It looks like this fails on `geopandas/tests/test_geom_methods.py::TestGeomMethods::test_crs_warning` 

A test that used to check for a warning now fails with a hard assertion.  Did master become more strict about this?

**Comment by jorisvandenbossche** [comment]
It is actually one of the commits in this PR that added that warning: https://github.com/geopandas/geopandas/pull/587/commits/832a5efd70b7d15f6733e5a4ff47966551d57046

Apparently there is going on something different with the (preserving of the) crs in `intersection` and possibly other methods.

**Comment by jorisvandenbossche** [comment]
So:

with cython branch (crs is not preserved in intersection method):
```
In [1]: from shapely.geometry import Point, LineString, Polygon

In [3]: from geopandas import *

In [4]: t1 = Polygon([(0, 0), (1, 0), (1, 1)])
   ...: t2 = Polygon([(0, 0), (1, 1), (0, 1)])
   ...: g3 = GeoSeries([t1, t2])

In [5]: g3.crs = {'init': 'epsg:4326', 'no_defs': True}

In [7]: g3.intersection(g3).crs

In [10]: g3_no_crs = g3.copy()

In [12]: g3_no_crs.crs = None

In [13]: g3.crs
Out[13]: {'init': 'epsg:4326', 'no_defs': True}

In [14]: g3.intersection(g3_no_crs).crs
```

on master:
```
In [1]: from shapely.geometry import Point, LineString, Polygon

In [2]: from geopandas import *

In [3]: t1 = Polygon([(0, 0), (1, 0), (1, 1)])
   ...: t2 = Polygon([(0, 0), (1, 1), (0, 1)])
   ...: g3 = GeoSeries([t1, t2])

In [4]: g3.crs = {'init': 'epsg:4326', 'no_defs': True}

In [5]: g3.intersection(g3).crs
Out[5]: {'init': 'epsg:4326', 'no_defs': True}

In [6]: g3_no_crs = g3.copy()

In [7]: g3_no_crs.crs = None

In [8]: g3.crs
Out[8]: {'init': 'epsg:4326', 'no_defs': True}

In [10]: g3.intersection(g3_no_crs).crs
/home/joris/scipy/geopandas/geopandas/base.py:29: UserWarning: GeoSeries crs mismatch: {'init': 'epsg:4326', 'no_defs': True} and None
  other.crs))
Out[10]: {'init': 'epsg:4326', 'no_defs': True}
```

(didn't look yet at the code, might be easy fix)

**Comment by mrocklin** [comment]
The relevant function is likely here:

```python
def binary_geo(op, left, right):
    """ Binary operation on GeoSeries objects that returns a GeoSeries """
    from .geoseries import GeoSeries
    if isinstance(right, GeoPandasBase):
        left = left.geometry
        left, right = left.align(right.geometry)
        t = left._geometry_array
        o = right._geometry_array
        x = vectorized.vector_binary_geo(op, t.data, o.data)
        return GeoSeries(x, index=left.index, crs=left.crs)
    elif isinstance(right, BaseGeometry):
        x = vectorized.binary_geo(op, left._geometry_array.data, right)
        return GeoSeries(x, index=left.index, crs=left.crs)
    else:
        raise TypeError(type(left), type(right))
```

It looks like we only consider `left.crs` and disregard `right.crs` entirely.  We incorrectly assume that they are the same.  What is the right behavior here?

**Comment by jdmcbr** [comment]
My first inclination is that there should be crs check at the outset of the `if isinstance(right, GeoPandasBase):` block that produces a warning for a CRS mismatch similar to the one currently in `_geo_op` on master. That's not possible on operations on `BaseGeometry` instances though. I don't think that obviates the value of the check being applied to `GeoSeries` and `GeoDataFrame` instances though, and having the check there seems like it probably catches the likeliest cases where a user would want a warning (at least from my experience working with shapefiles in the wild).

**Comment by jorisvandenbossche** [comment]
The problem is not only that there is no warning (that is easily added, as @jdmcbr notes), but that also the crs is completely lost (and apparently non of the other tests capture this ..). The crs is passed correctly in `binary_geo`, but it seems it gets lost in the `align` step.

**Comment by jdmcbr** [comment]
@jorisvandenbossche D'oh, totally misinterpreted your example, and was thinking the missing crs in the final result was due to taking the crs from `left`. But of course in your example above `left` did have a defined crs.

**Pull request merged**
