### PR TITLE
Fix lint

### PR DESCRIPTION
**Pull request by tqa236**
I enabled a few more `ruff` rules, separating each rule into a commit.

### CODE REVIEW

**Comment by martinfleis** [comment]
I would personally keep RUF002 disabled. Those changed it caused lead to worse typography in docstrings and I don't see how that is an improvement. I don't mind the rest but also have no strong opinion about them. We mostly copied the list of disabled rules form pandas in the first place so didn't put a ton of thought into that.

**Comment by tqa236** [comment]
@martinfleis I can revert RUF002 if you think it causes more harm than good, but now that `pandas` also enables RUF002, do you think `geopandas` can follow suit?

Here's the latest `pandas` config: https://github.com/pandas-dev/pandas/blob/main/pyproject.toml#L328

**Comment by martinfleis** [comment]
I don't care much to be honest. Let's wait for some of the other maintainers to weigh in.

**Comment by jorisvandenbossche** [comment]
This is going to become subjective ;)

I would personally keep [PLR5501](https://github.com/geopandas/geopandas/pull/3150/commits/818d5a45499500bacbc3ee49a95c6be4dbf33545) disabled .. It's often a good idea to flatten those levels, but in some of the cases it changed, there is a code logic about having if/else, and each block in that having another if/else. Changing that to if/elif/else changes the flow of the code, and can potentially make it harder to follow the logic. I think this is a case where the person writing the code can make a better judgment than a linter with a fixed rule.

**Comment by martinfleis** [comment]
> This is going to become subjective ;)

My proposal is not to touch the rules exceptions we have now. Our capacity to deal with GeoPandas stuff is limited and this is super low on priority but can turn into a long discussion that is not worth it/we can't afford.

**Comment by jorisvandenbossche** [comment]
In general I don't care about things that are just stylistic (like in general black's formatting), that's just less things to think about. So if there are some stylistic rules that can be enabled (and auto-fixed, like black), I am OK with that. 
But PLR5501 is not just stylistic, it changes the structure of the code. For those I agree it might not be worth the debate at the moment.

**Comment by m-richards** [comment]
If it avoids us talking round in circles I am happy to keep the lint rules as they are right now. 

If forced to make a decision on these, I'd enable RUF001,2,3 (but don't really care) and keep PLR5501 disabled, while in certain situations it might make the code clearer, I don't think it universally does.

**Comment by tqa236** [comment]
Hello all, 

I understood from the discussion that changing the list of ignored rules is not a priority now, will close this PR.

**Pull request closed without merging**
