### PR TITLE
ENH: Implement sindex query in clip

### PR DESCRIPTION
**Pull request by adriangb**
Quick PR to implement the new spatial index capabilities in clip.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Cool! That nicely shows the benefits of the improved query interface ;)

**Comment by adriangb** [comment]
I have not run any benchmarks. However, based on the benchmarks I have run on just `query_bulk` and `sindex.intersection` I think this will be faster. Let me do some quick testing to confirm.

**Comment by adriangb** [comment]
Benchmarks added. Results:
| before     | after     | ratio | pygeos installed?    |   |
|------------|-----------|-------|----------------------|---|
| 1.37±0.09s | 927±40ms  | ~0.68 | clip.Bench.time_clip | Y |
| 3.03±0.1s  | 2.98±0.2s | 0.98  | clip.Bench.time_clip | N |

**Comment by adriangb** [comment]
Seems like we're ready to merge this one, so straightforward after those other huge PRs!

**Comment by martinfleis** [comment]
Thanks @adriangb! You did all the hard work before ;)

**Comment by adriangb** [comment]
Might want to restart this job @martinfleis : https://travis-ci.org/github/geopandas/geopandas/jobs/687544175

**Pull request merged**
