### PR TITLE
API: Only raise TypeError for non-geometry in fillna if there are missing values

### LINKED ISSUE #1149: fillna error with 0.6
When performing `fillna` with `numpy.nan` on the entire dataframe, I get this error in version 0.6:
```
~/miniconda/envs/geocube/lib/python3.6/site-packages/geopandas/array.py in fillna(self, value, method, limit)
    831         elif not isinstance(value, BaseGeometry):
    832             raise NotImplementedError(
--> 833                 "fillna currently only supports filling with a scalar geometry"
    834             )
    835 

NotImplementedError: fillna currently only supports filling with a scalar geometry
```

Is this expected? Future plans?

### PR DESCRIPTION
**Pull request by bnaul**
Fixes #1149, which was already closed but IMO could stand to be re-opened :)

cc @martinfleis

### CODE REVIEW

**Comment by martinfleis** [comment]
Can you make a tests for it? So we don't break it in the future again.

**Comment by bnaul** [comment]
done!

**Comment by martinfleis** [comment]
This one is nice to have, but I'd rather see `fillna(0)` on gdf where it 1) actually fills missing values, 2) raises `NotImplementedError` if there is a missing geometry value. To test the actual use cases, rather than the bare minimum.

**Comment by bnaul** [comment]
Thanks @martinfleis, that makes sense; pushed a new version that is a bit more comprehensive.

**Pull request merged**
