### PR TITLE
Add "embedded data"

### LINKED ISSUE #282: Include example data in distribution
Seems like it'd be helpful to have a simple spatial dataset included in the distribution that we can use when writing examples and which users can just import and play with (I know `igraph` does this). 

Something universal but not to big -- medium or low resolution map of country outlines? Maybe as a GeoSeries with also as a simple GeoDataFrame with population or something?

Here's public domain [shapefiles](http://www.naturalearthdata.com/) ([terms of use say no permission needed for any purpose](http://www.naturalearthdata.com/about/terms-of-use/))

### PR DESCRIPTION
**Pull request by nickeubank**
Closes #282

Simple implementation of included shapefiles. In this case, just simple (low-resolution) country map. I think it'll really help writing the updated docs to just be able to import a dataset the user can also just open.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Thanks for your work on this!

I think we have to think a little bit about the interface we want (how a user can fetch these data). Maybe worth a look at how other libraries do this). 
I also think the setup.py will have to be adapted to include these files in a distribution (http://docs.python.org/3.4/distutils/setupscript.html#installing-additional-files)

**Comment by nickeubank** [comment]
@jorisvandenbossche 

Open to suggestions on API. The string query format seems eminently flexible. I assume that, to avoid bloat, we'll never put a full library of shapefiles in the actual package, so this simple interface feels adequate to me. I don't see this as a core function, just a tool for examples and teaching, though this setup makes it expandable if we change our mind. 

If we ever want to provide access to more data, I think the way to do it is find a web API that delivers shapefiles so we don't have to include them all, but I don't know of any that exist ([though I have a query on the topic](http://gis.stackexchange.com/questions/186807/web-api-preferably-python-for-gis-data)).

Re: setup.py: the builds on Travis worked, so seems like we're ok, no? I've never distributed a package, but seems like the current structure works...

**Comment by nickeubank** [comment]
@jorisvandenbossche relatedly, having some issues with testing because I can't get `fiona` to install in an anaconda environment. Have you had any luck (on a mac)? pip, conda, and the ioos channels all fail. https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/qGfB4P3wNFg

**Comment by nickeubank** [comment]
(also, to be blunt, I think it's probably more important that we get things together than fully optimize the API at the moment. I'm only pushing this because it'll make the docs rewrite a lot easier. But I think getting out docs, fixing the install issues #237, and releasing 0.2 are kind of the priorities)

**Pull request closed without merging**
