### PR TITLE
PERF: improve overlay performance

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
This improves the performance of the overlay on the countries/capitals dataset from 25.9 s to 12.5 s on my computer.

I did not change the logic of the implementation (looking at that could maybe also give some additional performance reduction opportunities), but just optimized the current logic, including:
- not concatting inside the for loop, but collecting the row labels and concatting once after the for loop
- using `iat` instead of `ix`

Tested with (example from the docs):

```
import geopandas as gpd
world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))
capitals = gpd.read_file(gpd.datasets.get_path('naturalearth_cities'))
countries = world[['geometry', 'name']]
countries = countries.to_crs('+init=epsg:3395')[countries.name!="Antarctica"]
capitals = capitals.to_crs('+init=epsg:3395')
capitals['geometry']= capitals.buffer(500000)

gpd.overlay(countries, capitals, how='intersection')
```

TODO:
- [ ] add some more tests (including tests for dataframes with non default (0,1,2, ...) row indices)

### CODE REVIEW

**Comment by nickeubank** [comment]
Have you profiled this? I had assumed issues were coming from the use of `iterrows` at line 35?

**Comment by jorisvandenbossche** [comment]
Yes, I line profiled it, and the two calls to the `_extract_rings()` function only takes 0.6% of the time (of course, for this example).

**Comment by nickeubank** [comment]
@jorisvandenbossche oh, great! Shows the illustration of profiling rather than guessing. :)

**Comment by ozak** [comment]
Hi,

any advances on this? I have noticed that the overlay function is extremely slow in ``GeoPandas``. I am running an overlay on two dataframes, which in QGIS takes less than a minute to create and in GeoPandas is taking hours. The code I am using is 

    difference = gpt.overlay(europe, partofeu, how='difference')

The dataframes have 78 and 10 features respectively, so it should be pretty fast. Obviously I need this programmatically in order to analyze many different shapefiles.

I am running additional operations using ``intersection`` and It is almost as if it is not taking advantage of a spatial index. If I do the intersections using the code [here](http://geoffboeing.com/2016/10/r-tree-spatial-index-python/) and a spatial index, the results are pretty fast. Of course that requires me write code to generate the intersections, then create the features and another dataframe, which is what I suppose ``overlay`` does in the background, right?

Any ideas?

**Comment by ozak** [comment]
Here's some code I wrote that seems to outperform the ``gpt.overlay`` computation

    def spatial_overlays(df1, df2):
        # Spatial Index to create intersections
        spatial_index = df2.sindex
        df1['bbox'] = df1.geometry.apply(lambda x: x.bounds)
        df1['histreg']=df1.bbox.apply(lambda x:list(spatial_index.intersection(x)))
        pairs = df1['histreg'].to_dict()
        nei = []
        for i,j in pairs.items():
            for k in j:
                nei.append([i,k])
        
        pairs = gp.GeoDataFrame(nei, columns=['idx1','idx2'], crs=df1.crs)
        pairs = pairs.merge(df1, left_on='idx1', right_index=True)
        pairs = pairs.merge(df2, left_on='idx2', right_index=True, suffixes=['_1','_2'])
        pairs['Intersection'] = pairs.apply(lambda x: (x['geometry_1'].intersection(x['geometry_2'])).buffer(0), axis=1)
        pairs = gp.GeoDataFrame(pairs, columns=pairs.columns, crs=df1.crs)
        cols = pairs.columns.tolist()
        cols.remove('geometry_1')
        cols.remove('geometry_2')
        cols.remove('histreg')
        cols.remove('bbox')
        cols.remove('Intersection')
        dfinter = pairs[cols+['Intersection']].copy()
        dfinter.rename(columns={'Intersection':'geometry'}, inplace=True)
        dfinter = gp.GeoDataFrame(dfinter, columns=dfinter.columns, crs=pairs.crs)
        dfinter = dfinter.loc[dfinter.geometry.is_empty==False]
        return dfinter

**Comment by ozak** [comment]
An improved version that allows for ``intersection`` and ``difference``

    def spatial_overlays(df1, df2, how='intersection'):
        '''Compute overlay intersection of two 
            GeoPandasDataFrames df1 and df2
        '''
        df1 = df1.copy()
        df2 = df2.copy()
        df1['geometry'] = df1.geometry.buffer(0)
        df2['geometry'] = df2.geometry.buffer(0)
        if how=='intersection':
            # Spatial Index to create intersections
            spatial_index = df2.sindex
            df1['bbox'] = df1.geometry.apply(lambda x: x.bounds)
            df1['histreg']=df1.bbox.apply(lambda x:list(spatial_index.intersection(x)))
            pairs = df1['histreg'].to_dict()
            nei = []
            for i,j in pairs.items():
                for k in j:
                    nei.append([i,k])
            
            pairs = gp.GeoDataFrame(nei, columns=['idx1','idx2'], crs=df1.crs)
            pairs = pairs.merge(df1, left_on='idx1', right_index=True)
            pairs = pairs.merge(df2, left_on='idx2', right_index=True, suffixes=['_1','_2'])
            pairs['Intersection'] = pairs.apply(lambda x: (x['geometry_1'].intersection(x['geometry_2'])).buffer(0), axis=1)
            pairs = gp.GeoDataFrame(pairs, columns=pairs.columns, crs=df1.crs)
            cols = pairs.columns.tolist()
            cols.remove('geometry_1')
            cols.remove('geometry_2')
            cols.remove('histreg')
            cols.remove('bbox')
            cols.remove('Intersection')
            dfinter = pairs[cols+['Intersection']].copy()
            dfinter.rename(columns={'Intersection':'geometry'}, inplace=True)
            dfinter = gp.GeoDataFrame(dfinter, columns=dfinter.columns, crs=pairs.crs)
            dfinter = dfinter.loc[dfinter.geometry.is_empty==False]
            return dfinter
        elif how=='difference':
            spatial_index = df2.sindex
            df1['bbox'] = df1.geometry.apply(lambda x: x.bounds)
            df1['histreg']=df1.bbox.apply(lambda x:list(spatial_index.intersection(x)))
            df1['new_g'] = df1.apply(lambda x: reduce(lambda x, y: x.difference(y).buffer(0), [x.geometry]+list(df2.iloc[x.histreg].geometry)) , axis=1)
            df1.geometry = df1.new_g
            df1 = df1.loc[df1.geometry.is_empty==False].copy()
            df1.drop(['bbox', 'histreg', new_g], axis=1, inplace=True)
            return df1

**Comment by ozak** [comment]
Just ran a test using the example and data above

    %time gpd.overlay(countries, capitals, how='intersection')
    CPU times: user 36.5 s, sys: 357 ms, total: 36.8 s
    Wall time: 38.8 s

    %time spatial_overlays(countries, capitals, how='intersection')
    CPU times: user 1.53 s, sys: 11.3 ms, total: 1.54 s
    Wall time: 1.59 s

**Comment by jorisvandenbossche** [comment]
@ozak Thanks for looking into this! 

The main reason I never merged this PR, is that I wanted to add more tests to check the correctness of my perf changes to the function. But I got stuck with that, as I couldn't get it working, see https://github.com/geopandas/geopandas/pull/343

**Comment by DeoLeung** [comment]
@ozak 
Hi , I tried your intersection function and found a weird situation
```python
target = Polygon(...) # only 1
candidates = GeoDataFrame(...) # 500k

# slow but get more intersections
candidates[candicates.intersects(target) == True].intersection(target)

# fast but get a bit less intersection
spatial_overlays(GeoDataFrame({'geometry': [target]}, crs={'init': 'epsg:4326'}), cancidates, how='intersection')
```
Do you have any quick idea about it?

**Comment by DeoLeung** [comment]
after playing around with the data I figure out the reason `candidate` has duplicated index
which `sindex` may drop the duplicated ones whilst `intersects` go through all the geometry

I will create another issue for it, sorry for the noise :)

**Comment by ozak** [comment]
Are the duplicated indices repeated geometries? What happens if you `` reset_index``? In a sense I think it makes sense that repeated geometries end up being dropped, since the intersection is the same.

**Comment by DeoLeung** [comment]
@ozak originally there were 2 `candidates` GeoDataFrame of different geometries, and then created by `GeoDataFrame(pd.concat([df1, df2]))`, I added `ignore_index=True` solve the problem at the moment, but need further invest to see what happen in `sindex` on duplicates. (I tried some test cases, `sindex` returns the duplicates, which is fine, shall be the problem of later slicing)

**Comment by ozak** [comment]
Ok I finally had time to finish implementing the function. I still have to check out the tests, but comparing with ``qgis`` it seems to generate the same results (and as far as I can tell does not suffer from some of the problems mentioned in other places).

```python

def spatial_overlays(df1, df2, how='intersection', reproject=True):
    '''Compute overlay intersection of two 
        GeoPandasDataFrames df1 and df2
    '''
    df1 = df1.copy()
    df2 = df2.copy()
    df1['geometry'] = df1.geometry.buffer(0)
    df2['geometry'] = df2.geometry.buffer(0)
    if df1.crs!=df2.crs and reproject:
        print('Data has different projections.')
        print('Converted data to projection of first GeoPandas DatFrame')
        df2.to_crs(crs=df1.crs, inplace=True)
    if how=='intersection':
        # Spatial Index to create intersections
        spatial_index = df2.sindex
        df1['bbox'] = df1.geometry.apply(lambda x: x.bounds)
        df1['sidx']=df1.bbox.apply(lambda x:list(spatial_index.intersection(x)))
        pairs = df1['sidx'].to_dict()
        nei = []
        for i,j in pairs.items():
            for k in j:
                nei.append([i,k])
        pairs = gpd.GeoDataFrame(nei, columns=['idx1','idx2'], crs=df1.crs)
        pairs = pairs.merge(df1, left_on='idx1', right_index=True)
        pairs = pairs.merge(df2, left_on='idx2', right_index=True, suffixes=['_1','_2'])
        pairs['Intersection'] = pairs.apply(lambda x: (x['geometry_1'].intersection(x['geometry_2'])).buffer(0), axis=1)
        pairs = gpd.GeoDataFrame(pairs, columns=pairs.columns, crs=df1.crs)
        cols = pairs.columns.tolist()
        cols.remove('geometry_1')
        cols.remove('geometry_2')
        cols.remove('sidx')
        cols.remove('bbox')
        cols.remove('Intersection')
        dfinter = pairs[cols+['Intersection']].copy()
        dfinter.rename(columns={'Intersection':'geometry'}, inplace=True)
        dfinter = gpd.GeoDataFrame(dfinter, columns=dfinter.columns, crs=pairs.crs)
        dfinter = dfinter.loc[dfinter.geometry.is_empty==False]
        dfinter.drop(['idx1','idx2'], inplace=True, axis=1)
        return dfinter
    elif how=='difference':
        spatial_index = df2.sindex
        df1['bbox'] = df1.geometry.apply(lambda x: x.bounds)
        df1['sidx']=df1.bbox.apply(lambda x:list(spatial_index.intersection(x)))
        df1['new_g'] = df1.apply(lambda x: reduce(lambda x, y: x.difference(y).buffer(0), 
                                 [x.geometry]+list(df2.iloc[x.sidx].geometry)) , axis=1)
        df1.geometry = df1.new_g
        df1 = df1.loc[df1.geometry.is_empty==False].copy()
        df1.drop(['bbox', 'sidx', 'new_g'], axis=1, inplace=True)
        return df1
    elif how=='symmetric_difference':
        df1['idx1'] = df1.index.tolist()
        df2['idx2'] = df2.index.tolist()
        df1['idx2'] = np.nan
        df2['idx1'] = np.nan
        dfsym = df1.merge(df2, on=['idx1','idx2'], how='outer')
        dfsym['geometry'] = dfsym.geometry_x
        dfsym.loc[dfsym.geometry_y.isnull()==False, 'geometry'] = dfsym.loc[dfsym.geometry_y.isnull()==False, 'geometry_y']
        dfsym.drop(['geometry_x', 'geometry_y'], axis=1, inplace=True)
        dfsym = gpd.GeoDataFrame(dfsym, columns=dfsym.columns, crs=df1.crs)
        spatial_index = dfsym.sindex
        dfsym['bbox'] = dfsym.geometry.apply(lambda x: x.bounds)
        dfsym['sidx'] = dfsym.bbox.apply(lambda x:list(spatial_index.intersection(x)))
        dfsym['idx'] = dfsym.index.values
        dfsym.apply(lambda x: x.sidx.remove(x.idx), axis=1)
        dfsym['new_g'] = dfsym.apply(lambda x: reduce(lambda x, y: x.difference(y).buffer(0), 
                         [x.geometry]+list(dfsym.iloc[x.sidx].geometry)) , axis=1)
        dfsym.geometry = dfsym.new_g
        dfsym = dfsym.loc[dfsym.geometry.is_empty==False].copy()
        dfsym.drop(['bbox', 'sidx', 'idx', 'idx1','idx2', 'new_g'], axis=1, inplace=True)
        return dfsym
    elif how=='union':
        dfinter = spatial_overlays(df1, df2, how='intersection')
        dfsym = spatial_overlays(df1, df2, how='symmetric_difference')
        dfunion = dfinter.append(dfsym)
        dfunion.reset_index(inplace=True, drop=True)
        return dfunion
```

Some benchmarks

```python 
from shapely.geometry import Polygon
import geopandas as gpd
from functools import reduce

# Polygons
polys1 = gpd.GeoSeries([Polygon([(0,0), (2,0), (2,2), (0,2)]),Polygon([(2,2), (4,2), (4,4), (2,4)])])
polys1 = gpd.GeoSeries([Polygon([(0,0), (2,0), (2,2), (0,2)]),Polygon([(2,2), (4,2), (4,4), (2,4)])])
polys2 = gpd.GeoSeries([Polygon([(1,1), (3,1), (3,3), (1,3)]),Polygon([(3,3), (5,3), (5,5), (3,5)])])

# GeoDataframes
df1 = gpd.GeoDataFrame({'geometry': polys1, 'df1':[1,2]}, crs={'init': 'epsg:4326', 'no_defs': True})
df2 = gpd.GeoDataFrame({'geometry': polys2, 'df2':[1,2]}, crs={'init': 'epsg:4326', 'no_defs': True})
df1.to_file(pathout+'df1.shp')
df2.to_file(pathout+'df2.shp')

%timeit gpd.tools.overlay(df1, df2, 'intersection')
10 loops, best of 3: 40.9 ms per loop

%timeit spatial_overlays(df1, df2)
10 loops, best of 3: 23.1 ms per loop

%timeit gpd.tools.overlay(df1, df2, 'difference')
10 loops, best of 3: 43.4 ms per loop

%timeit spatial_overlays(df1, df2, how='difference')
100 loops, best of 3: 17.1 ms per loop

%timeit gpd.tools.overlay(df1, df2, 'symmetric_difference')
10 loops, best of 3: 60.1 ms per loop

%timeit gpd.tools.overlay(df1, df2, 'symmetric_difference')
10 loops, best of 3: 56.6 ms per loop

%timeit spatial_overlays(df1, df2, how='symmetric_difference')
10 loops, best of 3: 39.4 ms per loop

%timeit gpd.tools.overlay(df1, df2, 'union')
10 loops, best of 3: 66.5 ms per loop

%timeit spatial_overlays(df1, df2, how='union')
10 loops, best of 3: 67.3 ms per loop
```

Another benchmark using a larger set 

```python
world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))
capitals = gpd.read_file(gpd.datasets.get_path('naturalearth_cities'))
countries = world[['geometry', 'name']]
countries = countries.to_crs('+init=epsg:3395')[countries.name!="Antarctica"]
capitals = capitals.to_crs('+init=epsg:3395')
capitals['geometry']= capitals.buffer(500000)

df1 = countries
df2 = capitals


%timeit gpd.tools.overlay(df1, df2, 'intersection')
1 loop, best of 3: 38.7 s per loop

%timeit spatial_overlays(df1, df2)
1 loop, best of 3: 2.05 s per loop

%timeit gpd.tools.overlay(df1, df2, 'difference')
1 loop, best of 3: 30.5 s per loop

%timeit spatial_overlays(df1, df2, how='difference')
1 loop, best of 3: 2.18 s per loop

%timeit gpd.tools.overlay(df1, df2, 'symmetric_difference')
1 loop, best of 3: 36 s per loop

%timeit spatial_overlays(df1, df2, how='symmetric_difference')
1 loop, best of 3: 7 s per loop

%timeit gpd.tools.overlay(df1, df2, 'union')

1 loop, best of 3: 50.1 s per loop

%timeit spatial_overlays(df1, df2, how='union')
1 loop, best of 3: 9.55 s per loop
```

Seems it does perform better...increasingly with larger datasets. If someone wants to benchmark it using a massive dataset that would be great.

**Comment by nickeubank** [comment]
@ozak Amazing, thanks for this! You wanna submit as a PR with tools and we can look more at details of style, test coverage, etc.?

**Comment by ozak** [comment]
Sure...I was just trying to improve the tests, which still fail. I'll try a couple of extra things to see if I am able to solve it and then submit a PR.

**Comment by ozak** [comment]
Hi, I created a PR for this a while ago in case it has not been seen....
GH-#429

**Comment by arobrien** [comment]
Hi, I'm trying to get on top of this Overlay stuff. I've read this conversation, but it's not clear whether PR #429 is supposed to replace this one, or whether this can be merged, and then #429 afterwards. I have a little bit of capacity over the next couple of weeks to help out.

Anyway, on the issue of differing results, I have explored the difference between @ozak's proposed algorithm, and the current (geopandas 0.3) overlay algorithm in the following GIST: https://gist.github.com/arobrien/427249e54bd2a496bccd4f619a96db6d

I note that:
- The old (current) method gives incomplete results, when input polygons overlap, whereas the new method gives the full intersection.
- The old (current) method gives fractured results, which would need a further merge step to eliminate duplicated key-pairs, whereas the new method does not - although it appears that this may be the desired behaviour for some people.
- In the old (current) method, the result for a single key-pair can be changed by the inclusion (or exclusion) of a 2nd object in one of the input GeoDataFrame's, whereas the new method avoids this side-effect.
- The new method is much faster than the old (current) method.

I also note that neither of these methodologies follows the behaviour one would expect from a conceptual merge_spatial() operation, in the Pandas paradigm. From my point of view, consistency with Pandas should be a goal of GeoPandas, although I'm not sure whether having separate overlay() and merge_spatial() functions which do almost the same thing would be desireable.

**Comment by Casyfill** [comment]
for some reason this new function fails for my use case (see here: https://github.com/geopandas/geopandas/issues/677)

**Comment by jorisvandenbossche** [comment]
@arobrien Sorry for the late answer, and thanks for chiming in. If you would still have some time to help out with this the coming weeks, that would certainly be welcome. 
I am trying to get an overview now, and will try to push forward some things.

> I also note that neither of these methodologies follows the behaviour one would expect from a conceptual merge_spatial() operation, in the Pandas paradigm. From my point of view, consistency with Pandas should be a goal of GeoPandas, although I'm not sure whether having separate overlay() and merge_spatial() functions which do almost the same thing would be desireable.

Can you explain this a bit in more detail? 
I think the `overlay` method has not really an equivalent in pandas itself. We do have a `sjoin` (spatial join) function, and this one is more comparable with pandas' `merge/join` (the main difference is that the merging key is not a column, but a calculated spatial relationship).

**Pull request closed without merging**
