### PR TITLE
MAINT: Fiona 1.10 compat for zip files

### LINKED ISSUE #3207: MAINT: Fiona 1.10 support
In our CI builds our fiona tests are failing against the 1.10a wheels, as a new path opening API is introduced (https://github.com/Toblerity/Fiona/pull/1331/files). We use `fiona.parse_path`, `fiona.path.ParsedPath`, `fiona.path.UnparsedPath` and `fiona.path.ParsedPath.from_uri(path)` at a quick glance. Now I think if we'd imported `fiona.path` instead of getting it relative to `import fiona` we'd just hit a warning that these will be removed in fiona 2.0 instead of hard crashes, but we may as well look at solving the root problem right now.

Edit: had a bit of a look and it seems to keep the same level of convenience witth zipfiles we might need to either vendor some things from fiona (or use the private internals), or use fsspec or similar

### PR DESCRIPTION
**Pull request by m-richards**
Closes #3207. It's worth looking at the diff before 12393dc773bc5213538ee3751fa53a72ec353180. I was originally intending to just fix the zipfile case and still depend on the internal details to push down the road until fiona 1.11/  fiona 2 for a future break. But I was looking into how we could replace this, and it actually seemed simpler to pinch the pyogrio logic for this, than to work out how to come up with a minimal equivalent of the fiona path classes - which we only want specifically for this purpose.

Not sure how we feel about introducing the new code / duplication.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
> Not sure how we feel about introducing the new code / duplication.

I am personally fine with doing that. It's indeed some duplication, but then we also are more robust against future Fiona changes (and most of the effort of re-writing this outside of Fiona was already done in pyogrio)

To what extent did you cut down the pyogrio code? Would it be easier to just copy-paste it verbatim, even if that includes some features we don't need, so it's easier to update it later in case pyogrio would update / fix things?

**Comment by jorisvandenbossche** [comment]
> To what extent did you cut down the pyogrio code? Would it be easier to just copy-paste it verbatim, even if that includes some features we don't need, so it's easier to update it later in case pyogrio would update / fix things?

Ah, looking at the code in pyogrio, I suppose it's mostly the `buffer_to_virtual_file` call, that's indeed something we have to remove here (and some completely unrelated helpers like `_preprocess_options_key_value`, that's of course fine to leave out)

**Comment by m-richards** [comment]
> > To what extent did you cut down the pyogrio code? Would it be easier to just copy-paste it verbatim, even if that includes some features we don't need, so it's easier to update it later in case pyogrio would update / fix things?
> 
> Ah, looking at the code in pyogrio, I suppose it's mostly the `buffer_to_virtual_file` call, that's indeed something we have to remove here (and some completely unrelated helpers like `_preprocess_options_key_value`, that's of course fine to leave out)

The functions that we use are unchanged, it was just the imports and other unused stuff

**Comment by jorisvandenbossche** [comment]
Yeah, I essentially wrote that piece of code in pyogrio by taking fiona's code (at the time) and simplifying it for just what we needed (eg we didn't need to class structure for just the internal usage)

**Comment by martinfleis** [comment]
Can you re-enable that test path we limited to pyogrio in #3209? To test the original issue.

**Review by martinfleis — APPROVED** [review]
Looks good to me! Thanks!

**Review by jorisvandenbossche — APPROVED** [review]
Thanks!

**Pull request merged**
