### PR TITLE
BUG: colorbar did not match normalised colors

### LINKED ISSUE #697: Pass keywords to colorbar construction
Hey all,
Amazing tool – thank you so much for putting it together and managing it so well.

I'm sure there is an easy fix to this, but I'm having trouble accessing the legend object from a chloropleth plot. I'd imagine ax.get_legend() should return it, but that doesn't seem to be the case.

My endgoal is simply to put the colormap horizontally beneath my figure – so if there's a very easy way to do that let me know. Thank you so much!

### PR DESCRIPTION
**Pull request by martinfleis**
In current version, if you use normalisation, colorbar does not represent true color scheme as it is always normalized linear between min and max. This PR fixes the behaviour and normalises colorbar using the same scheme, so the results should match. 

It should resolve issue like https://github.com/geopandas/geopandas/issues/697#issuecomment-515499696 . 

```
gdf = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))
gdf['random'] = np.random.gamma(2, 2, len(gdf)) - 2

vmin, vmax, vcenter = gdf.random.min(), gdf.random.max(), 0
divnorm = colors.DivergingNorm(vmin=vmin, vcenter=vcenter, vmax=vmax)

gdf.plot(column='random', cmap='RdBu', legend=True, norm=divnorm)
```
Before:
before
After:
after

Closes #697

### CODE REVIEW

**Comment by martinfleis** [comment]
Probably resolves  #393, but that issue is super unclear.

**Comment by jorisvandenbossche** [comment]
Fixed the conflict after merging the other PR

**Comment by jorisvandenbossche** [comment]
This is giving some errors. It might be that the test needs to be updated now the other PR is merged.

**Comment by martinfleis** [comment]
Tests should be fixed now. I'll wait for CI and merge.

**Pull request merged**
